#!/usr/bin/env python3
"""Build canonical CSV metric evidence cards and rolling-window package manifests.

This script converts valid rows from the Corporate Sustainability Tracker
processed CSV into deterministic CSV metric evidence cards. It also creates
parameterized rolling-window package manifests for downstream W2 evidence-card
RAG experiments.

Design boundary:
- Evidence cards are source-centric and permanent.
- Rolling-window membership belongs to package manifests, not to cards.
- No LLM is used during preprocessing.
- CSV retrieval_text is generated by deterministic template filling.

Expected project layout:
    data/
      processed/results/esg_indicators_postprocessed.csv
      raw/datasets/companies.csv
      raw/datasets/indicator_metadata.csv
    evidence/
      canonical/
      builds/

Example:
    python script/data_2_evidence/csv_2_evidence.py \
      --data-root data \
      --evidence-root evidence \
      --target-years 2021 2022 2023 \
      --csv-window-years 3 \
      --csv-lag-years 0 \
      --pdf-window-years 2 \
      --pdf-lag-years 1 \
      --selected-company-ids config/selected_companies.txt \
      --overwrite
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import shutil
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Literal

import pandas as pd


Mode = Literal["cards-and-packages", "cards-only", "packages-only"]


SCRIPT_VERSION = "csv_2_evidence_v1.0"
CSV_CARD_SCHEMA_VERSION = "csv_metric_card_v1"
BUILD_CONFIG_SCHEMA_VERSION = "evidence_build_config_v1"
PACKAGE_MANIFEST_SCHEMA_VERSION = "evidence_package_manifest_v1"
PROCESSING_METHOD = "deterministic_csv_metric_card_builder_v1"
RETRIEVAL_TEXT_TEMPLATE_VERSION = "deterministic_csv_metric_template_v1"

REQUIRED_ESG_COLUMNS = {
    "company_id",
    "year",
    "data_point_id",
    "data_point_description",
    "model_output_valid",
    "value_final",
}

OPTIONAL_ESG_COLUMNS = {
    "company_year",
    "model_output",
    "unit_final",
    "type_standard",
}

INDICATOR_COLUMNS = [
    "data_point_id",
    "topic",
    "discl_req",
    "discl_req_label",
    "label",
    "standard",
    "standard_topic",
    "context",
    "specification",
]

ACCEPTANCE_CRITERIA = {
    "phase_1_input_validation": [
        "All required input files exist.",
        "The ESG indicator CSV exposes all required source columns.",
        "Rolling-window parameters are positive and deterministic.",
        "Selected companies, if supplied, are parsed into stable company IDs.",
    ],
    "phase_2_canonical_cards": [
        "Only rows with model_output_valid == True and non-empty value_final become csv_metric cards.",
        "Each evidence_id follows csv::{company_id}::{source_year}::{data_point_id}.",
        "Each card has source_type='csv' and evidence_type='csv_metric'.",
        "Each card has non-empty deterministic retrieval_text.",
        "No card contains target_reporting_year, retrieval rank, prompt label, or support label.",
    ],
    "phase_3_canonical_storage": [
        "Per-company metadata is written under evidence/canonical/companies/{company_slug}__{company_id}/metadata/.",
        "Per-company source-row snapshots are written by source year.",
        "Per-company JSONL cards and global JSONL index are written.",
        "A CSV build summary and JSON integrity report are written.",
    ],
    "phase_4_package_manifests": [
        "Each build has a separate evidence/builds/{build_name}/ folder.",
        "build_config.json records every rolling-window parameter and input path.",
        "Each Company x Target Reporting Year package manifest stores csv/pdf source years.",
        "Manifest evidence_card_ids reference canonical evidence cards without duplicating card payloads.",
    ],
    "phase_5_integrity_checks": [
        "Generated evidence IDs are unique.",
        "All package references exist in the canonical card index.",
        "Manifest CSV source years equal the requested rolling-window rule.",
        "PDF source years respect pdf_lag_years and remain placeholders until PDF scripts are implemented.",
    ],
}


@dataclass
class CompanyMeta:
    company_id: str
    company_slug: str
    company_name: str
    isin: str | None = None
    country: str | None = None
    primary_sics_sector: str | None = None
    metadata_years: list[int] = field(default_factory=list)
    selection_reason: str | None = None
    source_dataset: str | None = None

    def folder_name(self) -> str:
        return f"{self.company_slug}__{self.company_id}"

    def to_json(self) -> dict[str, Any]:
        return {
            "company_id": self.company_id,
            "company_slug": self.company_slug,
            "company_name": self.company_name,
            "isin": self.isin,
            "country": self.country,
            "primary_sics_sector": self.primary_sics_sector,
            "metadata_years": self.metadata_years,
            "selection_reason": self.selection_reason,
            "source_dataset": self.source_dataset,
            "schema_version": "company_metadata_v1",
        }


@dataclass
class BuildStats:
    raw_rows_seen: int = 0
    rows_after_filters: int = 0
    eligible_rows: int = 0
    cards_written: int = 0
    duplicate_source_keys_seen: int = 0
    duplicate_evidence_ids_seen: int = 0
    missing_indicator_metadata_rows: int = 0
    companies_written: set[str] = field(default_factory=set)
    source_years_seen: set[int] = field(default_factory=set)
    touched_files: set[Path] = field(default_factory=set)
    evidence_ids: set[str] = field(default_factory=set)
    evidence_id_to_source_year: dict[str, int] = field(default_factory=dict)
    company_year_ids: dict[str, dict[int, list[str]]] = field(
        default_factory=lambda: defaultdict(lambda: defaultdict(list))
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert processed ESG CSV rows into canonical CSV metric evidence "
            "cards and parameterized rolling-window package manifests."
        )
    )

    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--evidence-root", type=Path, default=Path("evidence"))
    parser.add_argument(
        "--mode",
        choices=["cards-and-packages", "cards-only", "packages-only"],
        default="cards-and-packages",
        help=(
            "cards-and-packages builds canonical cards and package manifests; "
            "cards-only builds only canonical cards; packages-only reuses existing canonical cards."
        ),
    )

    parser.add_argument(
        "--target-years",
        type=int,
        nargs="+",
        default=[2021, 2022, 2023],
        help="Target reporting years for package manifests.",
    )
    parser.add_argument("--csv-window-years", type=int, default=3)
    parser.add_argument("--csv-lag-years", type=int, default=0)
    parser.add_argument("--pdf-window-years", type=int, default=2)
    parser.add_argument("--pdf-lag-years", type=int, default=1)

    parser.add_argument(
        "--source-year-min",
        type=int,
        default=None,
        help=(
            "Optional lower bound for canonical CSV card source years. "
            "If omitted, the required CSV rolling-window years are used."
        ),
    )
    parser.add_argument(
        "--source-year-max",
        type=int,
        default=None,
        help=(
            "Optional upper bound for canonical CSV card source years. "
            "If omitted, the required CSV rolling-window years are used."
        ),
    )
    parser.add_argument(
        "--all-source-years",
        action="store_true",
        help="Build canonical cards for all available CSV source years.",
    )

    parser.add_argument(
        "--selected-company-ids",
        type=Path,
        default=None,
        help=(
            "Optional text or CSV file containing selected company IDs. "
            "CSV files should contain a company_id column; plain text accepts one ID per line."
        ),
    )
    parser.add_argument(
        "--company-limit",
        type=int,
        default=None,
        help=(
            "Optional deterministic pilot limit when no selected-company file is provided. "
            "Companies are selected from companies.csv sorted by company name and ID."
        ),
    )

    parser.add_argument(
        "--build-name",
        type=str,
        default=None,
        help="Optional output folder name under evidence/builds/.",
    )
    parser.add_argument(
        "--chunksize",
        type=int,
        default=200_000,
        help="Number of source CSV rows to process per pandas chunk.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing build folder and canonical CSV output files touched by this run.",
    )

    return parser.parse_args()


def acceptance_report() -> None:
    print("\nAcceptance criteria")
    for phase, criteria in ACCEPTANCE_CRITERIA.items():
        print(f"  {phase}:")
        for criterion in criteria:
            print(f"    - {criterion}")
    print()


def pass_check(name: str, detail: str = "") -> None:
    message = f"[PASS] {name}"
    if detail:
        message += f" - {detail}"
    print(message)


def warn_check(name: str, detail: str = "") -> None:
    message = f"[WARN] {name}"
    if detail:
        message += f" - {detail}"
    print(message)


def fail(message: str) -> None:
    raise RuntimeError(message)


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass
    return re.sub(r"\s+", " ", str(value)).strip()


def slugify(value: str, fallback: str = "company") -> str:
    text = clean_text(value).lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text or fallback


def json_safe(value: Any) -> Any:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    if hasattr(value, "item"):
        return value.item()
    return value


def bool_series(series: pd.Series) -> pd.Series:
    if series.dtype == bool:
        return series.fillna(False)
    normalized = series.astype(str).str.strip().str.lower()
    return normalized.isin({"true", "1", "yes", "y", "t"})


def relative_to_or_absolute(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def write_json(path: Path, payload: Any, *, overwrite: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        fail(f"Refusing to overwrite existing JSON file: {path}")
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def prepare_append_file(path: Path, stats: BuildStats, *, overwrite: bool) -> bool:
    """Prepare an append target and return whether a header should be written."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path not in stats.touched_files:
        if path.exists():
            if overwrite:
                path.unlink()
            else:
                fail(f"Output file already exists. Use --overwrite or choose another output: {path}")
        stats.touched_files.add(path)
        return True
    return False


def append_jsonl(path: Path, records: Iterable[dict[str, Any]], stats: BuildStats, *, overwrite: bool) -> None:
    prepare_append_file(path, stats, overwrite=overwrite)
    with path.open("a", encoding="utf-8") as output:
        for record in records:
            output.write(json.dumps(record, ensure_ascii=False) + "\n")


def append_csv(path: Path, df: pd.DataFrame, stats: BuildStats, *, overwrite: bool) -> None:
    write_header = prepare_append_file(path, stats, overwrite=overwrite)
    df.to_csv(path, mode="a", index=False, header=write_header)


def rolling_years(target_year: int, window_years: int, lag_years: int = 0) -> list[int]:
    end_year = target_year - lag_years
    start_year = end_year - window_years + 1
    return list(range(start_year, end_year + 1))


def generated_build_name(args: argparse.Namespace) -> str:
    years = sorted(args.target_years)
    base = (
        f"csvwin{args.csv_window_years}_csvlag{args.csv_lag_years}_"
        f"pdfwin{args.pdf_window_years}_pdflag{args.pdf_lag_years}_"
        f"ty{years[0]}-{years[-1]}"
    )
    if args.selected_company_ids:
        token = hashlib.sha1(str(args.selected_company_ids).encode("utf-8")).hexdigest()[:7]
        return f"{base}_sel{token}"
    if args.company_limit:
        return f"{base}_limit{args.company_limit}"
    return base


def required_csv_source_years(args: argparse.Namespace) -> list[int] | None:
    if args.all_source_years:
        return None
    if args.source_year_min is not None or args.source_year_max is not None:
        if args.source_year_min is None or args.source_year_max is None:
            fail("--source-year-min and --source-year-max must be provided together.")
        if args.source_year_min > args.source_year_max:
            fail("--source-year-min cannot be greater than --source-year-max.")
        return list(range(args.source_year_min, args.source_year_max + 1))

    years: set[int] = set()
    for target_year in args.target_years:
        years.update(rolling_years(target_year, args.csv_window_years, args.csv_lag_years))
    return sorted(years)


def validate_args_and_paths(args: argparse.Namespace) -> dict[str, Path]:
    if not args.target_years:
        fail("At least one target year is required.")
    if any(year <= 0 for year in args.target_years):
        fail("Target years must be positive integers.")
    for name in ["csv_window_years", "pdf_window_years"]:
        if getattr(args, name) < 1:
            fail(f"--{name.replace('_', '-')} must be >= 1.")
    for name in ["csv_lag_years", "pdf_lag_years"]:
        if getattr(args, name) < 0:
            fail(f"--{name.replace('_', '-')} must be >= 0.")
    if args.chunksize < 1:
        fail("--chunksize must be >= 1.")

    data_root = args.data_root
    paths = {
        "esg": data_root / "processed" / "results" / "esg_indicators_postprocessed.csv",
        "companies": data_root / "raw" / "datasets" / "companies.csv",
        "indicators": data_root / "raw" / "datasets" / "indicator_metadata.csv",
    }

    if args.mode in {"cards-and-packages", "cards-only"}:
        for label, path in paths.items():
            if not path.exists():
                fail(f"Required input file not found for {label}: {path}")

        header = pd.read_csv(paths["esg"], nrows=0)
        missing = sorted(REQUIRED_ESG_COLUMNS - set(header.columns))
        if missing:
            fail(f"Missing required columns in {paths['esg']}: {missing}")

    if args.selected_company_ids and not args.selected_company_ids.exists():
        fail(f"Selected-company file not found: {args.selected_company_ids}")

    pass_check(
        "phase_1_input_validation",
        "input paths, required columns, and rolling-window arguments are valid",
    )
    return paths


def load_selected_company_table(path: Path | None) -> tuple[set[str] | None, dict[str, dict[str, Any]]]:
    if path is None:
        return None, {}

    if path.suffix.lower() == ".csv":
        df = pd.read_csv(path)
        if "company_id" not in df.columns:
            if len(df.columns) == 1:
                df = df.rename(columns={df.columns[0]: "company_id"})
            else:
                fail(f"Selected company CSV must contain a company_id column: {path}")
        df["company_id"] = df["company_id"].map(clean_text)
        df = df[df["company_id"].ne("")]
        overrides = {
            row["company_id"]: {key: json_safe(value) for key, value in row.items()}
            for row in df.to_dict(orient="records")
        }
        return set(df["company_id"]), overrides

    selected_ids: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        selected_ids.add(text.split(",")[0].strip())
    return selected_ids, {company_id: {"company_id": company_id} for company_id in selected_ids}


def load_indicator_metadata(path: Path) -> pd.DataFrame:
    indicators = pd.read_csv(path, low_memory=False)
    if "id" in indicators.columns and "data_point_id" not in indicators.columns:
        indicators = indicators.rename(columns={"id": "data_point_id"})
    if "data_point_id" not in indicators.columns:
        fail("indicator_metadata.csv must contain id or data_point_id.")
    for column in INDICATOR_COLUMNS:
        if column not in indicators.columns:
            indicators[column] = None
    indicators = indicators[INDICATOR_COLUMNS].drop_duplicates("data_point_id", keep="first")
    return indicators


def load_company_metadata(
    path: Path,
    selected_ids: set[str] | None,
    selected_overrides: dict[str, dict[str, Any]],
    company_limit: int | None,
) -> dict[str, CompanyMeta]:
    companies = pd.read_csv(path, low_memory=False)
    if "firm" not in companies.columns:
        fail("companies.csv must contain the firm column.")

    companies = companies.copy()
    companies["company_id"] = companies["firm"].map(clean_text)
    if "year" in companies.columns:
        companies["year_numeric"] = pd.to_numeric(companies["year"], errors="coerce")
    else:
        companies["year_numeric"] = None

    if selected_ids is None:
        company_rows = companies.sort_values(
            by=[column for column in ["name", "company_id", "year_numeric"] if column in companies.columns],
            kind="stable",
        )
        unique_ids = [company_id for company_id in company_rows["company_id"].dropna().unique() if company_id]
        if company_limit is not None:
            if company_limit < 1:
                fail("--company-limit must be >= 1 when provided.")
            selected_ids = set(unique_ids[:company_limit])
        else:
            selected_ids = set(unique_ids)

    metadata: dict[str, CompanyMeta] = {}
    for company_id in sorted(selected_ids):
        rows = companies[companies["company_id"] == company_id].copy()
        override = selected_overrides.get(company_id, {})

        if rows.empty:
            company_name = clean_text(override.get("company_name")) or clean_text(override.get("name")) or company_id
            company_slug = clean_text(override.get("company_slug")) or slugify(company_name, fallback=company_id[:8])
            metadata[company_id] = CompanyMeta(
                company_id=company_id,
                company_slug=company_slug,
                company_name=company_name,
                selection_reason=clean_text(override.get("selection_reason")) or None,
                source_dataset=str(path),
            )
            continue

        rows = rows.sort_values("year_numeric", na_position="first")
        latest = rows.iloc[-1].to_dict()
        company_name = (
            clean_text(override.get("company_name"))
            or clean_text(override.get("name"))
            or clean_text(latest.get("name"))
            or company_id
        )
        company_slug = clean_text(override.get("company_slug")) or slugify(company_name, fallback=company_id[:8])
        years = sorted(
            int(year)
            for year in rows["year_numeric"].dropna().unique().tolist()
        )

        metadata[company_id] = CompanyMeta(
            company_id=company_id,
            company_slug=company_slug,
            company_name=company_name,
            isin=clean_text(override.get("isin")) or clean_text(latest.get("isin")) or None,
            country=clean_text(override.get("country")) or clean_text(latest.get("country")) or None,
            primary_sics_sector=(
                clean_text(override.get("primary_sics_sector"))
                or clean_text(latest.get("primary_sics_sector"))
                or None
            ),
            metadata_years=years,
            selection_reason=clean_text(override.get("selection_reason")) or None,
            source_dataset=str(path),
        )

    return metadata


def canonical_paths(evidence_root: Path) -> dict[str, Path]:
    canonical_root = evidence_root / "canonical"
    return {
        "root": canonical_root,
        "companies": canonical_root / "companies",
        "indexes": canonical_root / "indexes",
        "all_cards": canonical_root / "indexes" / "all_csv_metric_cards.jsonl",
        "summary": canonical_root / "indexes" / "csv_build_summary.csv",
        "integrity": canonical_root / "indexes" / "csv_integrity_report.json",
    }


def company_root(evidence_root: Path, company: CompanyMeta) -> Path:
    return canonical_paths(evidence_root)["companies"] / company.folder_name()


def construct_retrieval_text(card_fields: dict[str, Any]) -> str:
    value_text = clean_text(card_fields.get("value_text"))
    unit = clean_text(card_fields.get("unit"))
    value_phrase = f"{value_text}{f' {unit}' if unit else ''}"
    return (
        f"Company: {clean_text(card_fields.get('company_name'))}. "
        f"Reporting year: {int(card_fields.get('source_year'))}. "
        f"ESG topic: {clean_text(card_fields.get('esg_topic'))}. "
        f"ESRS standard: {clean_text(card_fields.get('standard'))}. "
        f"Disclosure requirement: {clean_text(card_fields.get('discl_req'))}. "
        f"Indicator: {clean_text(card_fields.get('metric'))}. "
        f"Value: {value_phrase}."
    )


def construct_csv_metric_card(
    row: dict[str, Any],
    company: CompanyMeta,
    source_file: str,
) -> dict[str, Any]:
    source_year = int(row["year"])
    data_point_id = clean_text(row["data_point_id"])
    metric = clean_text(row.get("data_point_description"))
    indicator_label = clean_text(row.get("label"))

    value_raw = row.get("value_final")
    value_text = clean_text(value_raw)
    unit = clean_text(row.get("unit_final"))

    card = {
        "evidence_id": f"csv::{company.company_id}::{source_year}::{data_point_id}",
        "source_type": "csv",
        "evidence_type": "csv_metric",
        "company_id": company.company_id,
        "company_slug": company.company_slug,
        "company_name": company.company_name,
        "isin": company.isin,
        "country": company.country,
        "primary_sics_sector": company.primary_sics_sector,
        "source_year": source_year,
        "company_year": clean_text(row.get("company_year")) or f"{company.company_id}_{source_year}",
        "data_point_id": data_point_id,
        "metric": metric,
        "indicator_label": indicator_label or None,
        "esg_topic": clean_text(row.get("topic")) or None,
        "standard": clean_text(row.get("standard")) or None,
        "standard_topic": clean_text(row.get("standard_topic")) or None,
        "discl_req": clean_text(row.get("discl_req")) or None,
        "discl_req_label": clean_text(row.get("discl_req_label")) or None,
        "type_standard": clean_text(row.get("type_standard")) or None,
        "value": json_safe(value_raw),
        "value_text": value_text,
        "unit": unit or None,
        "retrieval_text": None,
        "source_file": source_file,
        "source_key": f"{company.company_id}_{source_year}_{data_point_id}",
        "model_output": clean_text(row.get("model_output")) or None,
        "model_output_valid": True,
        "schema_version": CSV_CARD_SCHEMA_VERSION,
        "processing_method": PROCESSING_METHOD,
        "retrieval_text_template": RETRIEVAL_TEXT_TEMPLATE_VERSION,
    }
    card["retrieval_text"] = construct_retrieval_text(card)
    return card


def write_company_metadata_files(
    evidence_root: Path,
    companies: dict[str, CompanyMeta],
    *,
    overwrite: bool,
) -> None:
    for company in companies.values():
        path = company_root(evidence_root, company) / "metadata" / "company_metadata.json"
        write_json(path, company.to_json(), overwrite=overwrite)


def build_canonical_cards(args: argparse.Namespace, paths: dict[str, Path]) -> tuple[BuildStats, dict[str, CompanyMeta]]:
    selected_ids, selected_overrides = load_selected_company_table(args.selected_company_ids)
    companies = load_company_metadata(
        paths["companies"],
        selected_ids,
        selected_overrides,
        args.company_limit,
    )
    indicators = load_indicator_metadata(paths["indicators"])
    indicator_lookup = indicators.copy()

    canonical = canonical_paths(args.evidence_root)
    canonical["indexes"].mkdir(parents=True, exist_ok=True)

    stats = BuildStats()
    source_years = required_csv_source_years(args)
    selected_ids_final = set(companies.keys())

    if source_years is None:
        source_year_detail = "all source years"
    else:
        source_year_detail = ",".join(str(year) for year in source_years)
    print(f"Canonical CSV card source years: {source_year_detail}")
    print(f"Selected companies: {len(selected_ids_final):,}")

    write_company_metadata_files(args.evidence_root, companies, overwrite=args.overwrite)

    source_file_label = relative_to_or_absolute(paths["esg"], args.data_root.parent if args.data_root.parent else Path.cwd())

    # Prepare global output early so existing files fail fast when --overwrite is not used.
    prepare_append_file(canonical["all_cards"], stats, overwrite=args.overwrite)

    chunk_iterator = pd.read_csv(paths["esg"], chunksize=args.chunksize, low_memory=False)
    seen_source_keys: set[tuple[str, int, str]] = set()

    for chunk_index, chunk in enumerate(chunk_iterator, start=1):
        stats.raw_rows_seen += len(chunk)
        for column in OPTIONAL_ESG_COLUMNS:
            if column not in chunk.columns:
                chunk[column] = None

        chunk = chunk.copy()
        chunk["company_id"] = chunk["company_id"].map(clean_text)
        chunk["year"] = pd.to_numeric(chunk["year"], errors="coerce")
        chunk = chunk[chunk["year"].notna()].copy()
        chunk["year"] = chunk["year"].astype(int)

        if source_years is not None:
            chunk = chunk[chunk["year"].isin(source_years)]
        if selected_ids_final:
            chunk = chunk[chunk["company_id"].isin(selected_ids_final)]

        if chunk.empty:
            continue

        stats.rows_after_filters += len(chunk)
        stats.source_years_seen.update(int(year) for year in chunk["year"].unique().tolist())

        # Join indicator metadata. This is deterministic and does not change source facts.
        enriched = chunk.merge(
            indicator_lookup[INDICATOR_COLUMNS],
            on="data_point_id",
            how="left",
            suffixes=("", "_indicator"),
            validate="many_to_one",
        )
        stats.missing_indicator_metadata_rows += int(enriched["standard"].isna().sum())

        # Write source-row snapshots before the evidence eligibility filter.
        for (company_id, year), group in enriched.groupby(["company_id", "year"], sort=True):
            company = companies.get(company_id)
            if company is None:
                continue
            source_rows_path = (
                company_root(args.evidence_root, company)
                / "csv"
                / "source_rows"
                / f"{int(year)}.csv"
            )
            append_csv(source_rows_path, group, stats, overwrite=args.overwrite)
            stats.companies_written.add(company_id)

        valid = bool_series(enriched["model_output_valid"])
        non_empty_value = enriched["value_final"].map(clean_text).ne("")
        eligible = enriched[valid & non_empty_value].copy()
        stats.eligible_rows += len(eligible)

        if eligible.empty:
            print(f"Processed chunk {chunk_index}: filtered rows={len(enriched):,}, cards=0")
            continue

        records_by_company: dict[str, list[dict[str, Any]]] = defaultdict(list)
        records_by_company_year: dict[tuple[str, int], list[dict[str, Any]]] = defaultdict(list)
        global_records: list[dict[str, Any]] = []

        for row in eligible.to_dict(orient="records"):
            company_id = clean_text(row["company_id"])
            company = companies.get(company_id)
            if company is None:
                continue

            source_year = int(row["year"])
            data_point_id = clean_text(row["data_point_id"])
            source_key_tuple = (company_id, source_year, data_point_id)
            if source_key_tuple in seen_source_keys:
                stats.duplicate_source_keys_seen += 1
            seen_source_keys.add(source_key_tuple)

            card = construct_csv_metric_card(row, company, source_file_label)
            evidence_id = card["evidence_id"]
            if evidence_id in stats.evidence_ids:
                stats.duplicate_evidence_ids_seen += 1
                continue

            if not clean_text(card["retrieval_text"]):
                fail(f"Empty retrieval_text for evidence_id={evidence_id}")

            stats.evidence_ids.add(evidence_id)
            stats.evidence_id_to_source_year[evidence_id] = source_year
            stats.company_year_ids[company_id][source_year].append(evidence_id)

            records_by_company[company_id].append(card)
            records_by_company_year[(company_id, source_year)].append(card)
            global_records.append(card)

        for company_id, records in records_by_company.items():
            company = companies[company_id]
            path = company_root(args.evidence_root, company) / "csv" / "evidence_cards" / "csv_metric_cards.jsonl"
            append_jsonl(path, records, stats, overwrite=args.overwrite)

        for (company_id, year), records in records_by_company_year.items():
            company = companies[company_id]
            path = (
                company_root(args.evidence_root, company)
                / "csv"
                / "evidence_cards"
                / "by_year"
                / f"{year}.jsonl"
            )
            append_jsonl(path, records, stats, overwrite=args.overwrite)

        append_jsonl(canonical["all_cards"], global_records, stats, overwrite=args.overwrite)
        stats.cards_written += len(global_records)

        print(
            f"Processed chunk {chunk_index}: "
            f"filtered rows={len(enriched):,}, cards={len(global_records):,}"
        )

    write_csv_build_summary(args, paths, stats, companies)
    run_canonical_integrity_checks(args, stats)
    pass_check(
        "phase_2_canonical_cards",
        f"{stats.cards_written:,} csv_metric cards generated with deterministic retrieval_text",
    )
    pass_check(
        "phase_3_canonical_storage",
        f"canonical outputs written under {canonical['root']}",
    )
    return stats, companies


def write_csv_build_summary(
    args: argparse.Namespace,
    paths: dict[str, Path],
    stats: BuildStats,
    companies: dict[str, CompanyMeta],
) -> None:
    canonical = canonical_paths(args.evidence_root)
    rows: list[dict[str, Any]] = []
    for company_id, company in companies.items():
        year_counts = {
            year: len(ids)
            for year, ids in sorted(stats.company_year_ids.get(company_id, {}).items())
        }
        rows.append(
            {
                "company_id": company_id,
                "company_slug": company.company_slug,
                "company_name": company.company_name,
                "csv_metric_cards": sum(year_counts.values()),
                "source_years_with_cards": json.dumps(sorted(year_counts.keys())),
                "cards_by_source_year": json.dumps(year_counts, sort_keys=True),
            }
        )

    canonical["indexes"].mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(canonical["summary"], index=False)

    report = {
        "script_version": SCRIPT_VERSION,
        "schema_version": "csv_integrity_report_v1",
        "created_at": now_utc_iso(),
        "input_files": {
            "esg_indicators": str(paths["esg"]),
            "companies": str(paths["companies"]),
            "indicator_metadata": str(paths["indicators"]),
        },
        "raw_rows_seen": stats.raw_rows_seen,
        "rows_after_filters": stats.rows_after_filters,
        "eligible_rows": stats.eligible_rows,
        "cards_written": stats.cards_written,
        "selected_company_count": len(companies),
        "source_years_seen": sorted(stats.source_years_seen),
        "duplicate_source_keys_seen": stats.duplicate_source_keys_seen,
        "duplicate_evidence_ids_seen": stats.duplicate_evidence_ids_seen,
        "missing_indicator_metadata_rows": stats.missing_indicator_metadata_rows,
        "required_csv_source_years": required_csv_source_years(args),
        "acceptance_criteria": ACCEPTANCE_CRITERIA,
    }
    write_json(canonical["integrity"], report, overwrite=True)


def run_canonical_integrity_checks(args: argparse.Namespace, stats: BuildStats) -> None:
    if stats.duplicate_evidence_ids_seen:
        fail(f"Duplicate evidence IDs detected: {stats.duplicate_evidence_ids_seen:,}")
    if stats.cards_written != len(stats.evidence_ids):
        fail(
            "Card count mismatch: cards_written does not match the unique evidence_id count."
        )
    if stats.cards_written == 0:
        warn_check(
            "canonical_cards_empty",
            "no cards were generated; check selected companies, source years, and source data",
        )
    if stats.missing_indicator_metadata_rows:
        warn_check(
            "indicator_metadata_missing",
            f"{stats.missing_indicator_metadata_rows:,} filtered source rows did not join indicator metadata",
        )

    canonical = canonical_paths(args.evidence_root)
    if not canonical["all_cards"].exists():
        fail(f"Global canonical card index missing: {canonical['all_cards']}")
    if not canonical["summary"].exists():
        fail(f"CSV build summary missing: {canonical['summary']}")
    if not canonical["integrity"].exists():
        fail(f"CSV integrity report missing: {canonical['integrity']}")


def load_existing_canonical_index(
    evidence_root: Path,
    selected_ids: set[str] | None,
) -> tuple[BuildStats, dict[str, CompanyMeta]]:
    canonical = canonical_paths(evidence_root)
    if not canonical["all_cards"].exists():
        fail(
            f"Cannot use --mode packages-only because canonical index does not exist: {canonical['all_cards']}"
        )

    stats = BuildStats()
    companies: dict[str, CompanyMeta] = {}

    with canonical["all_cards"].open("r", encoding="utf-8") as source:
        for line in source:
            if not line.strip():
                continue
            card = json.loads(line)
            company_id = clean_text(card.get("company_id"))
            if selected_ids is not None and company_id not in selected_ids:
                continue
            source_year = int(card["source_year"])
            evidence_id = clean_text(card["evidence_id"])

            stats.evidence_ids.add(evidence_id)
            stats.evidence_id_to_source_year[evidence_id] = source_year
            stats.company_year_ids[company_id][source_year].append(evidence_id)
            stats.cards_written += 1
            stats.companies_written.add(company_id)

            if company_id not in companies:
                companies[company_id] = CompanyMeta(
                    company_id=company_id,
                    company_slug=clean_text(card.get("company_slug")) or slugify(clean_text(card.get("company_name"))),
                    company_name=clean_text(card.get("company_name")) or company_id,
                    isin=clean_text(card.get("isin")) or None,
                    country=clean_text(card.get("country")) or None,
                    primary_sics_sector=clean_text(card.get("primary_sics_sector")) or None,
                    source_dataset=str(canonical["all_cards"]),
                )

    pass_check(
        "phase_2_canonical_cards",
        f"reused {stats.cards_written:,} existing canonical csv_metric cards",
    )
    return stats, companies


def build_config_payload(
    args: argparse.Namespace,
    paths: dict[str, Path] | None,
    build_name: str,
) -> dict[str, Any]:
    return {
        "build_name": build_name,
        "created_at": now_utc_iso(),
        "script": "script/data_2_evidence/csv_2_evidence.py",
        "script_version": SCRIPT_VERSION,
        "schema_version": BUILD_CONFIG_SCHEMA_VERSION,
        "target_years": sorted(args.target_years),
        "csv_window_years": args.csv_window_years,
        "csv_lag_years": args.csv_lag_years,
        "pdf_window_years": args.pdf_window_years,
        "pdf_lag_years": args.pdf_lag_years,
        "source_year_min": args.source_year_min,
        "source_year_max": args.source_year_max,
        "all_source_years": bool(args.all_source_years),
        "selected_company_ids_file": str(args.selected_company_ids) if args.selected_company_ids else None,
        "company_limit": args.company_limit,
        "mode": args.mode,
        "input_files": {
            "esg_indicators": str(paths["esg"]) if paths else None,
            "companies": str(paths["companies"]) if paths else None,
            "indicator_metadata": str(paths["indicators"]) if paths else None,
        },
        "canonical_card_index": str(canonical_paths(args.evidence_root)["all_cards"]),
        "output_root": str(args.evidence_root / "builds" / build_name),
        "rules": {
            "csv_card_selection": "model_output_valid == True AND value_final non-empty",
            "csv_retrieval_text": RETRIEVAL_TEXT_TEMPLATE_VERSION,
            "llm_used_in_preprocessing": False,
            "csv_includes_current_target_year_when_csv_lag_years_is_zero": args.csv_lag_years == 0,
            "pdf_excludes_current_target_year_when_pdf_lag_years_is_positive": args.pdf_lag_years > 0,
            "card_identity": "source-centric",
            "target_case_membership_location": "package_manifest",
        },
        "acceptance_criteria": ACCEPTANCE_CRITERIA,
    }


def build_package_manifests(
    args: argparse.Namespace,
    paths: dict[str, Path] | None,
    stats: BuildStats,
    companies: dict[str, CompanyMeta],
) -> None:
    build_name = args.build_name or generated_build_name(args)
    build_root = args.evidence_root / "builds" / build_name

    if build_root.exists():
        if args.overwrite:
            shutil.rmtree(build_root)
        else:
            fail(f"Build folder already exists. Use --overwrite or --build-name: {build_root}")

    build_root.mkdir(parents=True, exist_ok=True)
    write_json(
        build_root / "build_config.json",
        build_config_payload(args, paths, build_name),
        overwrite=True,
    )

    package_rows: list[dict[str, Any]] = []
    missing_reference_count = 0

    for company_id, company in sorted(companies.items(), key=lambda item: (item[1].company_slug, item[0])):
        for target_year in sorted(args.target_years):
            csv_years = rolling_years(target_year, args.csv_window_years, args.csv_lag_years)
            pdf_years = rolling_years(target_year, args.pdf_window_years, args.pdf_lag_years)

            package_metric_ids: list[str] = []
            for source_year in csv_years:
                package_metric_ids.extend(stats.company_year_ids.get(company_id, {}).get(source_year, []))

            for evidence_id in package_metric_ids:
                if evidence_id not in stats.evidence_ids:
                    missing_reference_count += 1

            excluded_pdf_years = []
            if target_year not in pdf_years:
                excluded_pdf_years.append(
                    {
                        "year": target_year,
                        "reason": "current_year_finalized_pdf_excluded_to_reduce_temporal_leakage",
                    }
                )

            package_id = f"{build_name}::{company.company_slug}::{target_year}"
            manifest = {
                "package_id": package_id,
                "build_name": build_name,
                "schema_version": PACKAGE_MANIFEST_SCHEMA_VERSION,
                "company_id": company.company_id,
                "company_slug": company.company_slug,
                "company_name": company.company_name,
                "target_reporting_year": target_year,
                "window_parameters": {
                    "csv_window_years": args.csv_window_years,
                    "csv_lag_years": args.csv_lag_years,
                    "pdf_window_years": args.pdf_window_years,
                    "pdf_lag_years": args.pdf_lag_years,
                },
                "included_source_years": {
                    "csv": csv_years,
                    "pdf": pdf_years,
                },
                "excluded_source_years": {
                    "pdf": excluded_pdf_years,
                },
                "evidence_card_ids": {
                    "csv_metric": package_metric_ids,
                    "pdf_narrative": [],
                    "pdf_table_row": [],
                    "pdf_table_markdown": [],
                },
                "evidence_card_counts": {
                    "csv_metric": len(package_metric_ids),
                    "pdf_narrative": 0,
                    "pdf_table_row": 0,
                    "pdf_table_markdown": 0,
                    "total": len(package_metric_ids),
                },
                "source_status": {
                    "csv_status": "implemented",
                    "pdf_status": "not_implemented",
                },
                "notes": [
                    "CSV cards are canonical source-centric records.",
                    "PDF evidence slots are placeholders for future pdf_narrative_2_evidence.py and pdf_table_2_evidence.py.",
                ],
            }

            manifest_path = (
                build_root
                / "companies"
                / company.folder_name()
                / "manifests"
                / f"package_{target_year}.json"
            )
            write_json(manifest_path, manifest, overwrite=True)

            package_rows.append(
                {
                    "package_id": package_id,
                    "build_name": build_name,
                    "company_id": company.company_id,
                    "company_slug": company.company_slug,
                    "company_name": company.company_name,
                    "target_reporting_year": target_year,
                    "csv_source_years": json.dumps(csv_years),
                    "pdf_source_years": json.dumps(pdf_years),
                    "csv_metric_cards": len(package_metric_ids),
                    "pdf_narrative_cards": 0,
                    "pdf_table_row_cards": 0,
                    "total_cards": len(package_metric_ids),
                    "manifest_path": str(manifest_path),
                }
            )

    if missing_reference_count:
        fail(f"Package manifests contain missing canonical card references: {missing_reference_count:,}")

    package_index = pd.DataFrame(package_rows)
    package_index.to_csv(build_root / "package_index.csv", index=False)

    run_package_integrity_checks(args, build_name, build_root, stats, package_index)
    pass_check(
        "phase_4_package_manifests",
        f"{len(package_rows):,} package manifests written under {build_root}",
    )
    pass_check(
        "phase_5_integrity_checks",
        "package references and rolling-window source years validated",
    )


def run_package_integrity_checks(
    args: argparse.Namespace,
    build_name: str,
    build_root: Path,
    stats: BuildStats,
    package_index: pd.DataFrame,
) -> None:
    if not (build_root / "build_config.json").exists():
        fail("Missing build_config.json.")
    if not (build_root / "package_index.csv").exists():
        fail("Missing package_index.csv.")

    errors: list[str] = []
    manifest_count = 0
    total_manifest_refs = 0

    for manifest_path in build_root.glob("companies/*/manifests/package_*.json"):
        manifest_count += 1
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        target_year = int(manifest["target_reporting_year"])
        expected_csv_years = rolling_years(target_year, args.csv_window_years, args.csv_lag_years)
        expected_pdf_years = rolling_years(target_year, args.pdf_window_years, args.pdf_lag_years)

        if manifest["included_source_years"]["csv"] != expected_csv_years:
            errors.append(f"{manifest_path}: CSV years do not match rolling-window rule.")
        if manifest["included_source_years"]["pdf"] != expected_pdf_years:
            errors.append(f"{manifest_path}: PDF years do not match rolling-window rule.")

        if args.pdf_lag_years > 0 and target_year in manifest["included_source_years"]["pdf"]:
            errors.append(f"{manifest_path}: target year appears in PDF source years despite positive pdf lag.")

        csv_ids = manifest["evidence_card_ids"]["csv_metric"]
        total_manifest_refs += len(csv_ids)
        for evidence_id in csv_ids:
            if evidence_id not in stats.evidence_ids:
                errors.append(f"{manifest_path}: missing evidence_id {evidence_id}")
                continue
            source_year = stats.evidence_id_to_source_year.get(evidence_id)
            if source_year not in expected_csv_years:
                errors.append(
                    f"{manifest_path}: evidence_id {evidence_id} has source year {source_year}, "
                    f"outside {expected_csv_years}"
                )

    expected_manifest_count = len(package_index)
    if manifest_count != expected_manifest_count:
        errors.append(
            f"Manifest count mismatch: found {manifest_count}, package_index has {expected_manifest_count}."
        )

    if errors:
        error_preview = "\n".join(errors[:20])
        fail(f"Package integrity checks failed with {len(errors)} error(s):\n{error_preview}")

    report = {
        "script_version": SCRIPT_VERSION,
        "schema_version": "package_integrity_report_v1",
        "created_at": now_utc_iso(),
        "build_name": build_name,
        "manifest_count": manifest_count,
        "total_manifest_csv_references": total_manifest_refs,
        "target_years": sorted(args.target_years),
        "csv_window_years": args.csv_window_years,
        "csv_lag_years": args.csv_lag_years,
        "pdf_window_years": args.pdf_window_years,
        "pdf_lag_years": args.pdf_lag_years,
        "checks_passed": True,
    }
    write_json(build_root / "package_integrity_report.json", report, overwrite=True)


def main() -> None:
    args = parse_args()
    acceptance_report()
    paths = validate_args_and_paths(args)

    if args.mode in {"cards-and-packages", "cards-only"}:
        stats, companies = build_canonical_cards(args, paths)
    else:
        selected_ids, _ = load_selected_company_table(args.selected_company_ids)
        stats, companies = load_existing_canonical_index(args.evidence_root, selected_ids)

    if args.mode in {"cards-and-packages", "packages-only"}:
        build_package_manifests(args, paths, stats, companies)

    print("\nCompleted successfully.")
    print(f"Mode: {args.mode}")
    print(f"Canonical cards available: {stats.cards_written:,}")
    if args.mode in {"cards-and-packages", "packages-only"}:
        print(f"Build folder: {args.evidence_root / 'builds' / (args.build_name or generated_build_name(args))}")


if __name__ == "__main__":
    main()
