#!/usr/bin/env python3
"""Build canonical PDF narrative/table evidence cards and update package manifests.

This script converts Corporate Sustainability Tracker PDF reports into deterministic
PDF evidence cards for the W2 transparent evidence-card RAG workflow. It mirrors
the design boundaries of csv_2_evidence.py:

Design boundary:
- Evidence cards are source-centric and permanent.
- Rolling-window membership belongs to package manifests, not to cards.
- No LLM is used during preprocessing.
- PDF narrative retrieval_text is the cleaned extracted PDF chunk.
- PDF table retrieval_text is generated by deterministic template filling from
  the extracted table row structure.

Expected project layout:
    data/
      processed/results/reports_per_company_year.csv
      raw/datasets/companies.csv
      raw/reports_pdf/*.pdf
    evidence/
      canonical/
      builds/

Example:
    python script/data_2_evidence/pdf_2_evidence.py \
      --data-root data \
      --evidence-root evidence \
      --target-years 2018 2019 2020 2021 2022 2023 \
      --csv-window-years 5 \
      --csv-lag-years 0 \
      --pdf-window-years 4 \
      --pdf-lag-years 1 \
      --selected-company-ids config/selected_companies.txt \
      --build-name full_companies_ty2018-2023_csvwin5_pdfwin4_pdflag1 \
      --mode cards-and-packages \
      --overwrite
"""

from __future__ import annotations

import argparse
import os
import json
import math
import re
import sys
import time
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Literal

import pandas as pd

try:  # PyMuPDF
    import fitz  # type: ignore
except ImportError:  # pragma: no cover - runtime dependency guard
    fitz = None

try:
    import pdfplumber  # type: ignore
except ImportError:  # pragma: no cover - runtime dependency guard
    pdfplumber = None


Mode = Literal["cards-and-packages", "cards-only", "packages-only", "pilot"]
ProgressStyle = Literal["auto", "bar", "line", "none"]


SCRIPT_VERSION = "pdf_2_evidence_v1.0"
PDF_NARRATIVE_CARD_SCHEMA_VERSION = "pdf_narrative_card_v1"
PDF_TABLE_ROW_CARD_SCHEMA_VERSION = "pdf_table_row_card_v2"
PDF_TABLE_MARKDOWN_CARD_SCHEMA_VERSION = "pdf_table_markdown_card_v1"
BUILD_CONFIG_SCHEMA_VERSION = "pdf_evidence_build_config_v1"
PDF_INTEGRITY_SCHEMA_VERSION = "pdf_integrity_report_v1"
PROCESSING_METHOD = "deterministic_pdf_evidence_builder_v1"
NARRATIVE_EXTRACTION_METHOD = "pymupdf_get_text_blocks_v1"
NARRATIVE_CLEANING_METHOD = "deterministic_pdf_text_cleaning_v1"
TABLE_EXTRACTION_METHOD = "pdfplumber_extract_tables_v1"
TABLE_CLEANING_METHOD = "deterministic_table_row_normalization_v1"

REPORT_FILENAME_RE = re.compile(
    r"^(?P<company_id>.+)_(?P<year>\d{4})_(?P<report_type>AR|SR)\.pdf$",
    re.IGNORECASE,
)

REPORT_TYPE_MAP = {
    "AR": "annual_report",
    "SR": "sustainability_report",
    "annual": "annual_report",
    "annual_report": "annual_report",
    "management_report": "annual_report",
    "integrated_report": "annual_report",
    "sustainability": "sustainability_report",
    "sustainability_report": "sustainability_report",
    "esg_report": "sustainability_report",
}

ACCEPTANCE_CRITERIA = {
    "phase_1_input_validation": [
        "All required input paths exist for the selected mode.",
        "Rolling-window parameters are positive and deterministic.",
        "Selected companies, if supplied, are parsed into stable company IDs.",
        "PyMuPDF is available when canonical PDF cards are built.",
        "pdfplumber is available when table extraction is enabled.",
    ],
    "phase_2_report_inventory": [
        "PDF reports are parsed into company_id, source_year, document_type, and source_file.",
        "Inventory rows are filtered by selected companies and required PDF source years.",
        "Missing inventory files are logged without silently creating evidence cards.",
        "Unparseable PDFs are logged and skipped unless they can be matched through the inventory.",
    ],
    "phase_3_narrative_cards": [
        "Each narrative card has source_type='pdf' and evidence_type='narrative'.",
        "Each narrative card has non-empty original_text and retrieval_text.",
        "For the baseline, retrieval_text equals original_text.",
        "No LLM rewriting, summarization, translation, or interpretation is used.",
        "Narrative cards contain no target_reporting_year, retrieval rank, prompt label, support label, or failure tag.",
    ],
    "phase_4_table_cards": [
        "Each table row card has source_type='pdf' and evidence_type='pdf_table_row'.",
        "Table row cards use column_headers, row_data, and cells as the source-preserving table structure.",
        "The v2 table schema does not use fixed ESG/GHG semantic fields such as dimensions or structured_values.",
        "Cell normalization is deterministic and preserves raw_text.",
        "Ambiguous or unreliable tables are logged with processing_warnings and manual_review_required.",
        "All table row cards enter the main index by default; deterministic manual-review warnings are preserved as audit metadata.",
    ],
    "phase_5_canonical_storage": [
        "Per-company PDF source extraction summaries are written.",
        "Per-company JSONL cards and by-year JSONL files are written.",
        "Global PDF card indexes are written under evidence/canonical/indexes/.",
        "A PDF build summary CSV and PDF integrity report JSON are written.",
    ],
    "phase_6_package_manifest_update": [
        "Existing package manifests are updated with canonical PDF evidence_card_ids.",
        "Manifest PDF source years match the requested rolling-window rule.",
        "Current-year finalized PDFs are excluded when pdf_lag_years > 0.",
        "All PDF package references exist in the canonical PDF indexes.",
        "Manifest total main cards exclude pdf_table_markdown unless explicitly used later.",
    ],
    "phase_7_integrity_checks": [
        "Generated evidence IDs are unique.",
        "Narrative retrieval_text equals original_text for all narrative cards produced in this run.",
        "Table row cards expose column_headers, row_data, and cells.",
        "PDF extraction failures and warnings are represented in extraction summaries or integrity reports.",
    ],
}

EXCLUDED_CARD_FIELDS = {
    "target_reporting_year",
    "case_id",
    "retrieval_rank",
    "retrieval_score",
    "prompt_label",
    "support_label",
    "claim_label",
    "failure_tag",
}


@dataclass
class CompanyMeta:
    company_id: str
    company_slug: str
    company_name: str
    isin: str | None = None
    country: str | None = None
    primary_sics_sector: str | None = None
    metadata_years: list[int] = field(default_factory=list)
    selection_reason: str | None = None
    source_dataset: str | None = None

    def folder_name(self) -> str:
        return f"{self.company_slug}__{self.company_id}"

    def to_json(self) -> dict[str, Any]:
        return {
            "company_id": self.company_id,
            "company_slug": self.company_slug,
            "company_name": self.company_name,
            "isin": self.isin,
            "country": self.country,
            "primary_sics_sector": self.primary_sics_sector,
            "metadata_years": self.metadata_years,
            "selection_reason": self.selection_reason,
            "source_dataset": self.source_dataset,
            "schema_version": "company_metadata_v1",
        }


@dataclass(frozen=True)
class ReportMeta:
    company_id: str
    source_year: int
    document_type: str
    source_file: str
    pdf_path: Path
    document_title: str | None = None
    inventory_source: str | None = None

    def report_token(self) -> str:
        prefix = "sr" if self.document_type == "sustainability_report" else "ar"
        return f"{prefix}{self.source_year}"


@dataclass
class PdfStats:
    pdfs_seen: int = 0
    pdfs_selected: int = 0
    pdfs_processed: int = 0
    pdfs_failed: int = 0
    missing_pdf_files: int = 0
    unparseable_pdf_files: int = 0
    pages_seen: int = 0
    pages_processed: int = 0
    pages_with_empty_text: int = 0
    narrative_cards_written: int = 0
    table_row_cards_written: int = 0
    table_markdown_cards_written: int = 0
    table_extraction_failures: int = 0
    manual_review_required_cards: int = 0
    main_index_excluded_cards: int = 0
    duplicate_evidence_ids_seen: int = 0
    companies_written: set[str] = field(default_factory=set)
    source_years_seen: set[int] = field(default_factory=set)
    touched_files: set[Path] = field(default_factory=set)
    evidence_ids: set[str] = field(default_factory=set)
    evidence_id_to_card_type: dict[str, str] = field(default_factory=dict)
    company_year_ids: dict[str, dict[int, dict[str, list[str]]]] = field(
        default_factory=lambda: defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    )
    warnings: list[dict[str, Any]] = field(default_factory=list)
    errors: list[dict[str, Any]] = field(default_factory=list)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Convert PDF reports into canonical PDF narrative/table evidence cards "
            "and update rolling-window package manifests."
        )
    )

    parser.add_argument("--data-root", type=Path, default=Path("data"))
    parser.add_argument("--evidence-root", type=Path, default=Path("evidence"))
    parser.add_argument(
        "--mode",
        choices=["cards-and-packages", "cards-only", "packages-only", "pilot"],
        default="cards-and-packages",
    )

    parser.add_argument("--target-years", type=int, nargs="+", default=[2021, 2022, 2023])
    parser.add_argument("--csv-window-years", type=int, default=3)
    parser.add_argument("--csv-lag-years", type=int, default=0)
    parser.add_argument("--pdf-window-years", type=int, default=2)
    parser.add_argument("--pdf-lag-years", type=int, default=1)

    parser.add_argument("--source-year-min", type=int, default=None)
    parser.add_argument("--source-year-max", type=int, default=None)
    parser.add_argument("--all-source-years", action="store_true")

    parser.add_argument("--selected-company-ids", type=Path, default=None)
    parser.add_argument("--company-limit", type=int, default=None)
    parser.add_argument("--build-name", type=str, default=None)
    parser.add_argument("--overwrite", action="store_true")

    parser.add_argument("--reports-dir", type=Path, default=None)
    parser.add_argument("--report-inventory", type=Path, default=None)
    parser.add_argument(
        "--include-unlisted-pdfs",
        action="store_true",
        help="Include PDFs found in reports-dir even if they are not in reports_per_company_year.csv.",
    )

    parser.add_argument("--extract-tables", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--include-table-markdown", action="store_true")
    parser.add_argument("--include-short-narrative", action="store_true")
    parser.add_argument("--narrative-min-words", type=int, default=40)
    parser.add_argument("--narrative-max-words", type=int, default=250)
    parser.add_argument("--narrative-min-chars", type=int, default=50)
    parser.add_argument("--max-pdfs", type=int, default=None)
    parser.add_argument("--max-pages-per-pdf", type=int, default=None)
    parser.add_argument(
        "--progress-style",
        choices=["auto", "bar", "line", "none"],
        default="auto",
        help="Progress display style for long PDF runs.",
    )
    parser.add_argument(
        "--workers",
        type=int,
        default=1,
        help=(
            "Number of parallel PDF worker processes. Default 1 preserves the "
            "original sequential behavior."
        ),
    )
    parser.add_argument(
        "--worker-chunksize",
        type=int,
        default=1,
        help="Chunksize passed to ProcessPoolExecutor.map for PDF tasks.",
    )

    return parser.parse_args()


class ProgressTracker:
    """Small dependency-free progress display for long server runs."""

    def __init__(self, total: int, label: str, style: ProgressStyle = "auto") -> None:
        self.total = max(total, 0)
        self.label = label
        self.current = 0
        self.last_line_len = 0
        if style == "auto":
            self.style: ProgressStyle = "bar" if sys.stderr.isatty() else "line"
        else:
            self.style = style
        self.started_at = time.time()

    def update(self, detail: str = "") -> None:
        self.current += 1
        if self.style == "none" or self.total == 0:
            return
        if self.style == "line":
            print(f"[{self.label}] {self.current:,}/{self.total:,} {detail}".rstrip())
            return
        width = 28
        ratio = min(1.0, self.current / self.total) if self.total else 1.0
        done = int(width * ratio)
        bar = "#" * done + "-" * (width - done)
        elapsed = max(time.time() - self.started_at, 0.001)
        rate = self.current / elapsed
        message = (
            f"\r[{self.label}] |{bar}| {self.current:,}/{self.total:,} "
            f"({ratio * 100:5.1f}%) {rate:5.2f} pdf/s {detail}"
        )
        sys.stderr.write(message.ljust(self.last_line_len))
        sys.stderr.flush()
        self.last_line_len = len(message)
        if self.current >= self.total:
            sys.stderr.write("\n")
            sys.stderr.flush()


def acceptance_report() -> None:
    print("\nAcceptance criteria")
    for phase, criteria in ACCEPTANCE_CRITERIA.items():
        print(f"  {phase}:")
        for criterion in criteria:
            print(f"    - {criterion}")
    print()


def pass_check(name: str, detail: str = "") -> None:
    message = f"[PASS] {name}"
    if detail:
        message += f" - {detail}"
    print(message)


def warn_check(name: str, detail: str = "") -> None:
    message = f"[WARN] {name}"
    if detail:
        message += f" - {detail}"
    print(message)


def fail(message: str) -> None:
    raise RuntimeError(message)


def now_utc_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def clean_text(value: Any) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass
    text = str(value)
    text = text.replace("\u00a0", " ")
    return re.sub(r"\s+", " ", text).strip()


def slugify(value: str, fallback: str = "company") -> str:
    text = clean_text(value).lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    text = text.strip("-")
    return text or fallback


def json_safe(value: Any) -> Any:
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    if hasattr(value, "item"):
        return value.item()
    return value


def relative_to_or_absolute(path: Path, root: Path) -> str:
    try:
        return str(path.resolve().relative_to(root.resolve()))
    except ValueError:
        return str(path)


def write_json(path: Path, payload: Any, *, overwrite: bool = True) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not overwrite:
        fail(f"Refusing to overwrite existing JSON file: {path}")
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def prepare_append_file(path: Path, stats: PdfStats, *, overwrite: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path not in stats.touched_files:
        if path.exists():
            if overwrite:
                path.unlink()
            else:
                fail(f"Output file already exists. Use --overwrite or choose another output: {path}")
        stats.touched_files.add(path)
        return True
    return False


def append_jsonl(path: Path, records: Iterable[dict[str, Any]], stats: PdfStats, *, overwrite: bool) -> None:
    prepare_append_file(path, stats, overwrite=overwrite)
    with path.open("a", encoding="utf-8") as output:
        for record in records:
            output.write(json.dumps(record, ensure_ascii=False) + "\n")


def rolling_years(target_year: int, window_years: int, lag_years: int = 0) -> list[int]:
    end_year = target_year - lag_years
    start_year = end_year - window_years + 1
    return list(range(start_year, end_year + 1))


def generated_build_name(args: argparse.Namespace) -> str:
    years = sorted(args.target_years)
    base = (
        f"csvwin{args.csv_window_years}_csvlag{args.csv_lag_years}_"
        f"pdfwin{args.pdf_window_years}_pdflag{args.pdf_lag_years}_"
        f"ty{years[0]}-{years[-1]}"
    )
    if args.selected_company_ids:
        token = re.sub(r"[^a-zA-Z0-9]+", "", str(args.selected_company_ids))[-7:] or "selected"
        return f"{base}_sel{token}"
    if args.company_limit:
        return f"{base}_limit{args.company_limit}"
    return base


def required_pdf_source_years(args: argparse.Namespace) -> list[int] | None:
    if args.all_source_years:
        return None
    if args.source_year_min is not None or args.source_year_max is not None:
        if args.source_year_min is None or args.source_year_max is None:
            fail("--source-year-min and --source-year-max must be provided together.")
        if args.source_year_min > args.source_year_max:
            fail("--source-year-min cannot be greater than --source-year-max.")
        return list(range(args.source_year_min, args.source_year_max + 1))

    years: set[int] = set()
    for target_year in args.target_years:
        years.update(rolling_years(target_year, args.pdf_window_years, args.pdf_lag_years))
    return sorted(years)


def canonical_paths(evidence_root: Path) -> dict[str, Path]:
    canonical_root = evidence_root / "canonical"
    return {
        "root": canonical_root,
        "companies": canonical_root / "companies",
        "indexes": canonical_root / "indexes",
        "all_narrative": canonical_root / "indexes" / "all_pdf_narrative_cards.jsonl",
        "all_table_rows": canonical_root / "indexes" / "all_pdf_table_row_cards.jsonl",
        "all_table_markdown": canonical_root / "indexes" / "all_pdf_table_markdown_cards.jsonl",
        "all_pdf_cards": canonical_root / "indexes" / "all_pdf_cards.jsonl",
        "summary": canonical_root / "indexes" / "pdf_build_summary.csv",
        "integrity": canonical_root / "indexes" / "pdf_integrity_report.json",
        "inventory_summary": canonical_root / "indexes" / "pdf_inventory_summary.csv",
    }


def company_root(evidence_root: Path, company: CompanyMeta) -> Path:
    return canonical_paths(evidence_root)["companies"] / company.folder_name()


def load_selected_company_table(path: Path | None) -> tuple[set[str] | None, dict[str, dict[str, Any]]]:
    if path is None:
        return None, {}

    if path.suffix.lower() == ".csv":
        df = pd.read_csv(path)
        if "company_id" not in df.columns:
            if len(df.columns) == 1:
                df = df.rename(columns={df.columns[0]: "company_id"})
            else:
                fail(f"Selected company CSV must contain a company_id column: {path}")
        df["company_id"] = df["company_id"].map(clean_text)
        df = df[df["company_id"].ne("")]
        overrides = {
            row["company_id"]: {key: json_safe(value) for key, value in row.items()}
            for row in df.to_dict(orient="records")
        }
        return set(df["company_id"]), overrides

    selected_ids: set[str] = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        text = line.strip()
        if not text or text.startswith("#"):
            continue
        selected_ids.add(text.split(",")[0].strip())
    return selected_ids, {company_id: {"company_id": company_id} for company_id in selected_ids}


def load_company_metadata(
    path: Path,
    selected_ids: set[str] | None,
    selected_overrides: dict[str, dict[str, Any]],
    company_limit: int | None,
) -> dict[str, CompanyMeta]:
    companies = pd.read_csv(path, low_memory=False)
    if "firm" not in companies.columns:
        fail("companies.csv must contain the firm column.")

    companies = companies.copy()
    companies["company_id"] = companies["firm"].map(clean_text)
    if "year" in companies.columns:
        companies["year_numeric"] = pd.to_numeric(companies["year"], errors="coerce")
    else:
        companies["year_numeric"] = None

    if selected_ids is None:
        company_rows = companies.sort_values(
            by=[column for column in ["name", "company_id", "year_numeric"] if column in companies.columns],
            kind="stable",
        )
        unique_ids = [company_id for company_id in company_rows["company_id"].dropna().unique() if company_id]
        if company_limit is not None:
            if company_limit < 1:
                fail("--company-limit must be >= 1 when provided.")
            selected_ids = set(unique_ids[:company_limit])
        else:
            selected_ids = set(unique_ids)

    metadata: dict[str, CompanyMeta] = {}
    for company_id in sorted(selected_ids):
        rows = companies[companies["company_id"] == company_id].copy()
        override = selected_overrides.get(company_id, {})

        if rows.empty:
            company_name = clean_text(override.get("company_name")) or clean_text(override.get("name")) or company_id
            company_slug = clean_text(override.get("company_slug")) or slugify(company_name, fallback=company_id[:8])
            metadata[company_id] = CompanyMeta(
                company_id=company_id,
                company_slug=company_slug,
                company_name=company_name,
                selection_reason=clean_text(override.get("selection_reason")) or None,
                source_dataset=str(path),
            )
            continue

        rows = rows.sort_values("year_numeric", na_position="first")
        latest = rows.iloc[-1].to_dict()
        company_name = (
            clean_text(override.get("company_name"))
            or clean_text(override.get("name"))
            or clean_text(latest.get("name"))
            or company_id
        )
        company_slug = clean_text(override.get("company_slug")) or slugify(company_name, fallback=company_id[:8])
        years = sorted(int(year) for year in rows["year_numeric"].dropna().unique().tolist())

        metadata[company_id] = CompanyMeta(
            company_id=company_id,
            company_slug=company_slug,
            company_name=company_name,
            isin=clean_text(override.get("isin")) or clean_text(latest.get("isin")) or None,
            country=clean_text(override.get("country")) or clean_text(latest.get("country")) or None,
            primary_sics_sector=(
                clean_text(override.get("primary_sics_sector"))
                or clean_text(latest.get("primary_sics_sector"))
                or None
            ),
            metadata_years=years,
            selection_reason=clean_text(override.get("selection_reason")) or None,
            source_dataset=str(path),
        )

    return metadata


def write_company_metadata_files(evidence_root: Path, companies: dict[str, CompanyMeta], *, overwrite: bool) -> None:
    for company in companies.values():
        path = company_root(evidence_root, company) / "metadata" / "company_metadata.json"
        write_json(path, company.to_json(), overwrite=overwrite)


def validate_args_and_paths(args: argparse.Namespace) -> dict[str, Path]:
    if not args.target_years:
        fail("At least one target year is required.")
    if any(year <= 0 for year in args.target_years):
        fail("Target years must be positive integers.")
    for name in ["csv_window_years", "pdf_window_years"]:
        if getattr(args, name) < 1:
            fail(f"--{name.replace('_', '-')} must be >= 1.")
    for name in ["csv_lag_years", "pdf_lag_years"]:
        if getattr(args, name) < 0:
            fail(f"--{name.replace('_', '-')} must be >= 0.")
    if args.narrative_min_words < 1 or args.narrative_max_words < args.narrative_min_words:
        fail("Narrative word thresholds must be positive and max >= min.")
    if args.max_pdfs is not None and args.max_pdfs < 1:
        fail("--max-pdfs must be >= 1 when provided.")
    if args.max_pages_per_pdf is not None and args.max_pages_per_pdf < 1:
        fail("--max-pages-per-pdf must be >= 1 when provided.")
    if args.workers < 1:
        fail("--workers must be >= 1.")
    if args.worker_chunksize < 1:
        fail("--worker-chunksize must be >= 1.")
    available_cpus = os.cpu_count() or 1
    try:
        available_cpus = len(os.sched_getaffinity(0))
    except AttributeError:
        pass
    if args.workers > available_cpus:
        warn_check(
            "workers_exceed_available_cpus",
            f"--workers {args.workers} exceeds detected CPUs {available_cpus}; continuing anyway",
        )

    data_root = args.data_root
    paths = {
        "companies": data_root / "raw" / "datasets" / "companies.csv",
        "reports_dir": args.reports_dir or data_root / "raw" / "reports_pdf",
        "report_inventory": args.report_inventory or data_root / "processed" / "results" / "reports_per_company_year.csv",
    }

    if args.mode in {"cards-and-packages", "cards-only", "pilot"}:
        if fitz is None:
            fail("PyMuPDF is required to build PDF cards. Install with: pip install pymupdf")
        if args.extract_tables and pdfplumber is None:
            fail("pdfplumber is required when --extract-tables is enabled. Install with: pip install pdfplumber")
        if not paths["companies"].exists():
            fail(f"Required companies.csv not found: {paths['companies']}")
        if not paths["reports_dir"].exists():
            fail(f"Required PDF report folder not found: {paths['reports_dir']}")
        if not paths["report_inventory"].exists():
            warn_check(
                "report_inventory_missing",
                f"{paths['report_inventory']} not found; falling back to PDF filename parsing only",
            )

    if args.mode in {"cards-and-packages", "packages-only"}:
        build_name = args.build_name or generated_build_name(args)
        build_root = args.evidence_root / "builds" / build_name
        if not build_root.exists():
            fail(
                f"Build folder does not exist for package update: {build_root}. "
                "Run csv_2_evidence.py first or use --mode cards-only."
            )

    if args.selected_company_ids and not args.selected_company_ids.exists():
        fail(f"Selected-company file not found: {args.selected_company_ids}")

    pass_check(
        "phase_1_input_validation",
        "input paths, dependencies, selected companies, and rolling-window arguments are valid",
    )
    return paths


def parse_report_filename(path: Path) -> ReportMeta | None:
    match = REPORT_FILENAME_RE.match(path.name)
    if not match:
        return None
    report_token = match.group("report_type").upper()
    return ReportMeta(
        company_id=match.group("company_id"),
        source_year=int(match.group("year")),
        document_type=REPORT_TYPE_MAP[report_token],
        source_file=path.name,
        pdf_path=path,
        inventory_source="filename",
    )


def choose_column(columns: Iterable[str], candidates: list[str]) -> str | None:
    lowered = {column.lower(): column for column in columns}
    for candidate in candidates:
        if candidate.lower() in lowered:
            return lowered[candidate.lower()]
    return None


def normalize_document_type(value: Any, source_file: str | None = None) -> str | None:
    text = clean_text(value).lower()
    text = re.sub(r"[^a-z0-9]+", "_", text).strip("_")
    if text in REPORT_TYPE_MAP:
        return REPORT_TYPE_MAP[text]
    if text.upper() in REPORT_TYPE_MAP:
        return REPORT_TYPE_MAP[text.upper()]
    if source_file:
        parsed = parse_report_filename(Path(source_file))
        if parsed:
            return parsed.document_type
    return None


def load_report_inventory(
    inventory_path: Path,
    reports_dir: Path,
    companies: dict[str, CompanyMeta],
    source_years: list[int] | None,
    include_unlisted_pdfs: bool,
    stats: PdfStats,
) -> list[ReportMeta]:
    records: dict[tuple[str, int, str, str], ReportMeta] = {}

    if inventory_path.exists():
        df = pd.read_csv(inventory_path, low_memory=False)
        company_col = choose_column(df.columns, ["company_id", "firm", "firm_id", "company"])
        year_col = choose_column(df.columns, ["source_year", "year", "reporting_year", "fiscal_year"])
        file_col = choose_column(
            df.columns,
            ["source_file", "filename", "file_name", "pdf_file", "report_file", "path", "pdf_path", "file"],
        )
        type_col = choose_column(df.columns, ["document_type", "report_type", "type", "report_category"])
        title_col = choose_column(df.columns, ["document_title", "title", "report_title"])

        if file_col is None:
            warn_check(
                "report_inventory_no_file_column",
                "falling back to filename parsing because report inventory has no recognized PDF file column",
            )
        else:
            for row in df.to_dict(orient="records"):
                source_file = clean_text(row.get(file_col))
                if not source_file.lower().endswith(".pdf"):
                    continue
                filename = Path(source_file).name
                fallback = parse_report_filename(Path(filename))

                company_id = clean_text(row.get(company_col)) if company_col else ""
                if not company_id and fallback:
                    company_id = fallback.company_id
                if not company_id:
                    stats.unparseable_pdf_files += 1
                    stats.warnings.append({"stage": "inventory", "source_file": filename, "warning": "missing_company_id"})
                    continue

                year_value = row.get(year_col) if year_col else None
                source_year: int | None = None
                try:
                    if clean_text(year_value):
                        source_year = int(float(clean_text(year_value)))
                except ValueError:
                    source_year = None
                if source_year is None and fallback:
                    source_year = fallback.source_year
                if source_year is None:
                    stats.unparseable_pdf_files += 1
                    stats.warnings.append({"stage": "inventory", "source_file": filename, "warning": "missing_source_year"})
                    continue

                document_type = normalize_document_type(row.get(type_col) if type_col else None, filename)
                if document_type is None and fallback:
                    document_type = fallback.document_type
                if document_type is None:
                    stats.unparseable_pdf_files += 1
                    stats.warnings.append({"stage": "inventory", "source_file": filename, "warning": "missing_document_type"})
                    continue

                pdf_path = Path(source_file)
                if not pdf_path.is_absolute():
                    pdf_path = reports_dir / filename

                document_title = clean_text(row.get(title_col)) if title_col else None
                meta = ReportMeta(
                    company_id=company_id,
                    source_year=int(source_year),
                    document_type=document_type,
                    document_title=document_title or None,
                    source_file=filename,
                    pdf_path=pdf_path,
                    inventory_source=str(inventory_path),
                )
                records[(meta.company_id, meta.source_year, meta.document_type, meta.source_file)] = meta

    if include_unlisted_pdfs or not records:
        for pdf_path in sorted(reports_dir.glob("*.pdf")):
            parsed = parse_report_filename(pdf_path)
            if parsed is None:
                stats.unparseable_pdf_files += 1
                stats.warnings.append({"stage": "inventory", "source_file": pdf_path.name, "warning": "unparseable_filename"})
                continue
            records.setdefault((parsed.company_id, parsed.source_year, parsed.document_type, parsed.source_file), parsed)

    stats.pdfs_seen = len(records)
    selected: list[ReportMeta] = []
    selected_company_ids = set(companies.keys())
    source_year_set = set(source_years) if source_years is not None else None

    for meta in sorted(records.values(), key=lambda item: (item.company_id, item.source_year, item.document_type, item.source_file)):
        if meta.company_id not in selected_company_ids:
            continue
        if source_year_set is not None and meta.source_year not in source_year_set:
            continue
        if not meta.pdf_path.exists():
            stats.missing_pdf_files += 1
            stats.warnings.append(
                {
                    "stage": "inventory",
                    "company_id": meta.company_id,
                    "source_file": meta.source_file,
                    "warning": "missing_pdf_file",
                    "expected_path": str(meta.pdf_path),
                }
            )
            continue
        selected.append(meta)

    stats.pdfs_selected = len(selected)
    pass_check(
        "phase_2_report_inventory",
        f"{stats.pdfs_selected:,} PDF reports selected from {stats.pdfs_seen:,} inventory candidates",
    )
    return selected


def clean_extracted_text(text: str) -> tuple[str, list[str]]:
    warnings: list[str] = []
    original = text or ""
    if "\u00ad" in original:
        original = original.replace("\u00ad", "")
        warnings.append("soft_hyphen_removed")
    repaired = re.sub(r"(?<=\w)-\s*\n\s*(?=\w)", "", original)
    if repaired != original:
        warnings.append("hyphenation_repaired")
    repaired = repaired.replace("\r", "\n")
    # Keep block-level text as one paragraph; collapse line breaks inside block.
    repaired = re.sub(r"[ \t]+", " ", repaired)
    repaired = re.sub(r"\s*\n\s*", " ", repaired)
    cleaned = re.sub(r"\s+", " ", repaired).strip()
    return cleaned, warnings


def word_count(text: str) -> int:
    return len(re.findall(r"\b\S+\b", text))


def approximate_token_count(text: str) -> int:
    # Deterministic lightweight approximation. Avoids tokenizer dependency.
    return max(1, math.ceil(len(text) / 4)) if text else 0


def looks_like_table_text(text: str) -> bool:
    if not text:
        return False
    digit_ratio = sum(ch.isdigit() for ch in text) / max(len(text), 1)
    has_many_numbers = len(re.findall(r"\d+(?:[,.]\d+)*", text)) >= 4
    has_separators = "|" in text or "\t" in text or bool(re.search(r"\s{3,}", text))
    return digit_ratio > 0.18 and (has_many_numbers or has_separators)


def split_long_text(text: str, max_words: int) -> list[str]:
    sentences = re.split(r"(?<=[.!?])\s+", text)
    chunks: list[str] = []
    current: list[str] = []
    current_words = 0
    for sentence in sentences:
        sentence = clean_text(sentence)
        if not sentence:
            continue
        sentence_words = word_count(sentence)
        if current and current_words + sentence_words > max_words:
            chunks.append(" ".join(current).strip())
            current = [sentence]
            current_words = sentence_words
        else:
            current.append(sentence)
            current_words += sentence_words
    if current:
        chunks.append(" ".join(current).strip())
    if len(chunks) == 1 and word_count(chunks[0]) > max_words * 1.5:
        # Last-resort deterministic split by words.
        words = chunks[0].split()
        chunks = [" ".join(words[index:index + max_words]) for index in range(0, len(words), max_words)]
    return chunks


def extract_pdf_text_blocks(pdf_path: Path, max_pages: int | None) -> tuple[list[dict[str, Any]], dict[str, Any]]:
    if fitz is None:
        fail("PyMuPDF is not available.")

    summary: dict[str, Any] = {
        "pages_total": 0,
        "pages_processed": 0,
        "warnings": [],
        "errors": [],
    }
    blocks: list[dict[str, Any]] = []

    try:
        document = fitz.open(pdf_path)  # type: ignore[union-attr]
    except Exception as exc:  # noqa: BLE001
        summary["errors"].append({"stage": "text_extraction", "warning": "parser_error", "error": str(exc)})
        return blocks, summary

    with document:
        page_count = len(document)
        summary["pages_total"] = page_count
        limit = min(page_count, max_pages) if max_pages is not None else page_count
        for page_index in range(limit):
            page_number = page_index + 1
            try:
                page = document[page_index]
                raw_blocks = page.get_text("blocks", sort=True)  # type: ignore[attr-defined]
                summary["pages_processed"] += 1
                if not raw_blocks:
                    summary["warnings"].append({"stage": "text_extraction", "page": page_number, "warning": "empty_extracted_text"})
                    continue
                page_block_count = 0
                for block in raw_blocks:
                    if len(block) < 5:
                        continue
                    raw_text = str(block[4])
                    cleaned, cleaning_warnings = clean_extracted_text(raw_text)
                    if not cleaned:
                        continue
                    blocks.append(
                        {
                            "page_number": page_number,
                            "block_index": page_block_count,
                            "raw_text": raw_text,
                            "cleaned_text": cleaned,
                            "processing_warnings": cleaning_warnings,
                        }
                    )
                    page_block_count += 1
                if page_block_count == 0:
                    summary["warnings"].append({"stage": "text_extraction", "page": page_number, "warning": "empty_extracted_text"})
            except Exception as exc:  # noqa: BLE001
                summary["errors"].append(
                    {"stage": "text_extraction", "page": page_number, "warning": "parser_error", "error": str(exc)}
                )
    return blocks, summary


def make_narrative_chunks(
    blocks: list[dict[str, Any]],
    *,
    min_words: int,
    max_words: int,
    min_chars: int,
    include_short: bool,
) -> list[dict[str, Any]]:
    chunks: list[dict[str, Any]] = []
    current_texts: list[str] = []
    current_pages: list[int] = []
    current_warnings: list[str] = []
    current_words = 0

    def flush() -> None:
        nonlocal current_texts, current_pages, current_warnings, current_words
        text = clean_text(" ".join(current_texts))
        if not text:
            current_texts, current_pages, current_warnings, current_words = [], [], [], 0
            return
        warnings = sorted(set(current_warnings))
        if len(text) < min_chars or word_count(text) < min_words:
            warnings.append("very_short_chunk")
            if not include_short and len(text) < min_chars:
                current_texts, current_pages, current_warnings, current_words = [], [], [], 0
                return
        if looks_like_table_text(text):
            warnings.append("possible_table_text")
        if len(set(current_pages)) > 1:
            warnings.append("page_break_joined")
        chunks.append(
            {
                "text": text,
                "page_start": min(current_pages) if current_pages else None,
                "page_end": max(current_pages) if current_pages else None,
                "processing_warnings": sorted(set(warnings)),
            }
        )
        current_texts, current_pages, current_warnings, current_words = [], [], [], 0

    for block in blocks:
        text = clean_text(block["cleaned_text"])
        if not text:
            continue
        text_words = word_count(text)
        if text_words > max_words:
            flush()
            for piece in split_long_text(text, max_words):
                piece_warnings = list(block.get("processing_warnings", []))
                if word_count(piece) < min_words:
                    piece_warnings.append("very_short_chunk")
                if looks_like_table_text(piece):
                    piece_warnings.append("possible_table_text")
                chunks.append(
                    {
                        "text": piece,
                        "page_start": block["page_number"],
                        "page_end": block["page_number"],
                        "processing_warnings": sorted(set(piece_warnings)),
                    }
                )
            continue

        if current_texts and current_words >= min_words and current_words + text_words > max_words:
            flush()

        current_texts.append(text)
        current_pages.append(int(block["page_number"]))
        current_warnings.extend(block.get("processing_warnings", []))
        current_words += text_words

        if current_words >= min_words:
            # Flush at paragraph/block boundary once target minimum is reached.
            flush()

    flush()
    return chunks


def construct_narrative_card(
    chunk: dict[str, Any],
    chunk_index: int,
    report: ReportMeta,
    company: CompanyMeta,
) -> dict[str, Any]:
    page_start = int(chunk["page_start"])
    page_end = int(chunk["page_end"])
    original_text = clean_text(chunk["text"])
    evidence_id = (
        f"pdf_narrative::{company.company_id}::{report.document_type}::{report.source_year}::"
        f"p{page_start:03d}::c{chunk_index:04d}"
    )
    card = {
        "evidence_id": evidence_id,
        "company_id": company.company_id,
        "company_slug": company.company_slug,
        "company_name": company.company_name,
        "isin": company.isin,
        "country": company.country,
        "primary_sics_sector": company.primary_sics_sector,
        "source_type": "pdf",
        "evidence_type": "narrative",
        "source_year": report.source_year,
        "document_type": report.document_type,
        "document_title": report.document_title,
        "source_file": report.source_file,
        "page_start": page_start,
        "page_end": page_end,
        "section_heading": None,
        "heading_path": [],
        "chunk_index": chunk_index,
        "original_text": original_text,
        "retrieval_text": original_text,
        "extraction_method": NARRATIVE_EXTRACTION_METHOD,
        "cleaning_method": NARRATIVE_CLEANING_METHOD,
        "processing_warnings": chunk.get("processing_warnings", []),
        "chunking_rule": "paragraph_oriented_40_250_words_v1",
        "token_count": approximate_token_count(original_text),
        "character_count": len(original_text),
        "include_in_main_index": True,
        "schema_version": PDF_NARRATIVE_CARD_SCHEMA_VERSION,
        "processing_method": PROCESSING_METHOD,
    }
    assert_no_excluded_card_fields(card)
    return card


def table_id_for(report: ReportMeta, page_number: int, table_index: int) -> str:
    return f"{report.report_token()}_p{page_number:03d}_t{table_index:02d}"


def make_unique_headers(raw_headers: list[Any]) -> tuple[list[str], list[str]]:
    warnings: list[str] = []
    seen: dict[str, int] = defaultdict(int)
    headers: list[str] = []
    for index, value in enumerate(raw_headers):
        header = clean_text(value)
        if not header:
            header = f"unnamed_column_{index}"
            warnings.append("empty_column_header")
        base = header
        seen[base] += 1
        if seen[base] > 1:
            header = f"{base}__{seen[base]}"
            warnings.append("duplicate_column_headers")
        headers.append(header)
    return headers, sorted(set(warnings))


def parse_number(text: str) -> float | int | None:
    value = clean_text(text)
    if not value:
        return None
    # Do not treat accounting parentheses as negative. Remove parentheses but warn elsewhere.
    value = value.strip()
    if value.startswith("(") and value.endswith(")"):
        value = value[1:-1].strip()
    value = value.replace("%", "")
    value = value.replace(",", "")
    value = re.sub(r"\s+", "", value)
    if re.fullmatch(r"[-+]?\d+", value):
        try:
            return int(value)
        except ValueError:
            return None
    if re.fullmatch(r"[-+]?\d*\.\d+", value):
        try:
            return float(value)
        except ValueError:
            return None
    return None


def normalize_cell(header: str, raw_text: Any) -> dict[str, Any]:
    raw = clean_text(raw_text)
    lower = raw.lower()
    header_lower = header.lower()
    warnings: list[str] = []
    normalized_value: Any = None
    value_type = "text"
    unit: str | None = None

    if raw == "" or lower in {"n/a", "na", "not applicable", "not disclosed", "-", "—", "–"}:
        value_type = "missing"
    elif raw.startswith("(") and raw.endswith(")") and parse_number(raw) is not None:
        value_type = "number"
        normalized_value = parse_number(raw)
        warnings.append("parenthesized_number_ambiguous")
    elif "%" in raw and parse_number(raw) is not None:
        value_type = "percent"
        normalized_value = parse_number(raw)
    elif ("year" in header_lower or "date" in header_lower) and re.fullmatch(r"(?:19|20)\d{2}", raw):
        value_type = "year"
        normalized_value = int(raw)
    elif "unit" in header_lower:
        value_type = "unit"
        unit = raw or None
    else:
        number = parse_number(raw)
        if number is not None:
            value_type = "number"
            normalized_value = number
        elif re.fullmatch(r"[A-Za-z0-9/%²³_\-]+", raw) and any(token in lower for token in ["co2", "tco", "mwh", "gwh", "kwh", "ton", "tonne", "eur", "usd", "percent"]):
            value_type = "unit"
            unit = raw

    return {
        "column_header": header,
        "raw_text": raw,
        "normalized_value": normalized_value,
        "value_type": value_type,
        "unit": unit,
        "processing_warnings": sorted(set(warnings)),
    }


def build_row_data(headers: list[str], row: list[Any]) -> tuple[dict[str, str], list[dict[str, Any]], list[str]]:
    warnings: list[str] = []
    adjusted = list(row)
    if len(adjusted) < len(headers):
        adjusted.extend([""] * (len(headers) - len(adjusted)))
        warnings.append("row_cell_count_mismatch")
    elif len(adjusted) > len(headers):
        adjusted = adjusted[: len(headers)]
        warnings.append("row_cell_count_mismatch")

    row_data: dict[str, str] = {}
    cells: list[dict[str, Any]] = []
    for index, header in enumerate(headers):
        raw = clean_text(adjusted[index])
        row_data[header] = raw
        cell = normalize_cell(header, raw)
        cell["column_index"] = index
        # Rebuild to keep stable key order.
        cells.append(
            {
                "column_index": cell["column_index"],
                "column_header": cell["column_header"],
                "raw_text": cell["raw_text"],
                "normalized_value": cell["normalized_value"],
                "value_type": cell["value_type"],
                "unit": cell["unit"],
                "processing_warnings": cell["processing_warnings"],
            }
        )
        warnings.extend(cell["processing_warnings"])
    return row_data, cells, sorted(set(warnings))


def construct_table_retrieval_text(
    company: CompanyMeta,
    report: ReportMeta,
    page_number: int,
    table_title: str | None,
    row_data: dict[str, str],
) -> str:
    source_label = report.document_type.replace("_", " ")
    table_label = f'table "{table_title}"' if table_title else "table"
    pairs = "; ".join(f"{key} = {value}" for key, value in row_data.items() if clean_text(value))
    return (
        f"Company: {company.company_name}. Source: {source_label} {report.source_year}, "
        f"page {page_number}, {table_label}. Table row: {pairs}."
    )


def markdown_for_row(headers: list[str], row_data: dict[str, str]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    sep_line = "| " + " | ".join("---" for _ in headers) + " |"
    row_line = "| " + " | ".join(row_data.get(header, "") for header in headers) + " |"
    return "\n".join([header_line, sep_line, row_line])


def construct_table_row_card(
    report: ReportMeta,
    company: CompanyMeta,
    page_number: int,
    table_index: int,
    row_index: int,
    headers: list[str],
    row_data: dict[str, str],
    cells: list[dict[str, Any]],
    warnings: list[str],
    table_title: str | None = None,
) -> dict[str, Any]:
    table_id = table_id_for(report, page_number, table_index)
    evidence_id = (
        f"pdf_table_row::{company.company_id}::{report.document_type}::{report.source_year}::"
        f"p{page_number:03d}::t{table_index:02d}::r{row_index:04d}"
    )
    non_empty_values = [value for value in row_data.values() if clean_text(value)]
    row_warnings = sorted(set(warnings))
    manual_review_required = bool(
        set(row_warnings)
        & {"row_cell_count_mismatch", "empty_column_header", "duplicate_column_headers", "table_header_alignment_uncertain"}
    )
    if not headers or not non_empty_values:
        manual_review_required = True
        row_warnings.append("empty_table_row")
    include_in_main_index = True
    original_row_text = " | ".join(row_data.get(header, "") for header in headers)
    retrieval_text = construct_table_retrieval_text(company, report, page_number, table_title, row_data)
    if manual_review_required:
        retrieval_text = retrieval_text.rstrip(".") + ". Table extraction requires manual review."

    card = {
        "evidence_id": evidence_id,
        "company_id": company.company_id,
        "company_slug": company.company_slug,
        "company_name": company.company_name,
        "isin": company.isin,
        "country": company.country,
        "primary_sics_sector": company.primary_sics_sector,
        "source_type": "pdf",
        "evidence_type": "pdf_table_row",
        "source_year": report.source_year,
        "document_type": report.document_type,
        "document_title": report.document_title,
        "source_file": report.source_file,
        "page_start": page_number,
        "page_end": page_number,
        "table_id": table_id,
        "table_index": table_index,
        "table_title": table_title,
        "section_heading": None,
        "row_index": row_index,
        "column_headers": headers,
        "row_data": row_data,
        "cells": cells,
        "original_table_row_text": original_row_text,
        "normalized_table_markdown": markdown_for_row(headers, row_data),
        "retrieval_text": retrieval_text,
        "extraction_method": TABLE_EXTRACTION_METHOD,
        "cleaning_method": TABLE_CLEANING_METHOD,
        "processing_warnings": sorted(set(row_warnings)),
        "manual_review_required": manual_review_required,
        "include_in_main_index": include_in_main_index,
        "schema_version": PDF_TABLE_ROW_CARD_SCHEMA_VERSION,
        "processing_method": PROCESSING_METHOD,
    }
    assert_no_excluded_card_fields(card)
    return card


def construct_table_markdown_card(
    report: ReportMeta,
    company: CompanyMeta,
    page_number: int,
    table_index: int,
    headers: list[str],
    rows: list[dict[str, str]],
    warnings: list[str],
    table_title: str | None = None,
) -> dict[str, Any]:
    table_id = table_id_for(report, page_number, table_index)
    evidence_id = f"pdf_table_markdown::{company.company_id}::{report.document_type}::{report.source_year}::p{page_number:03d}::t{table_index:02d}"
    markdown_lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join("---" for _ in headers) + " |"]
    for row_data in rows:
        markdown_lines.append("| " + " | ".join(row_data.get(header, "") for header in headers) + " |")
    markdown = "\n".join(markdown_lines)
    source_label = report.document_type.replace("_", " ")
    retrieval_text = (
        f"Company: {company.company_name}. Source: {source_label} {report.source_year}, "
        f"page {page_number}, table {table_index}. Full extracted table: {markdown}"
    )
    card = {
        "evidence_id": evidence_id,
        "company_id": company.company_id,
        "company_slug": company.company_slug,
        "company_name": company.company_name,
        "isin": company.isin,
        "country": company.country,
        "primary_sics_sector": company.primary_sics_sector,
        "source_type": "pdf",
        "evidence_type": "pdf_table_markdown",
        "source_year": report.source_year,
        "document_type": report.document_type,
        "document_title": report.document_title,
        "source_file": report.source_file,
        "page_start": page_number,
        "page_end": page_number,
        "table_id": table_id,
        "table_index": table_index,
        "table_title": table_title,
        "section_heading": None,
        "column_headers": headers,
        "normalized_table_markdown": markdown,
        "retrieval_text": retrieval_text,
        "extraction_method": TABLE_EXTRACTION_METHOD,
        "cleaning_method": TABLE_CLEANING_METHOD,
        "processing_warnings": sorted(set(warnings)),
        "manual_review_required": bool(warnings),
        "include_in_main_index": False,
        "schema_version": PDF_TABLE_MARKDOWN_CARD_SCHEMA_VERSION,
        "processing_method": PROCESSING_METHOD,
    }
    assert_no_excluded_card_fields(card)
    return card


def extract_table_cards(
    report: ReportMeta,
    company: CompanyMeta,
    *,
    max_pages: int | None,
    include_table_markdown: bool,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    if pdfplumber is None:
        fail("pdfplumber is not available.")

    row_cards: list[dict[str, Any]] = []
    markdown_cards: list[dict[str, Any]] = []
    summary: dict[str, Any] = {"warnings": [], "errors": [], "tables_seen": 0}

    try:
        with pdfplumber.open(report.pdf_path) as pdf:  # type: ignore[union-attr]
            pages = pdf.pages
            limit = min(len(pages), max_pages) if max_pages is not None else len(pages)
            for page_index in range(limit):
                page_number = page_index + 1
                try:
                    tables = pages[page_index].extract_tables() or []
                except Exception as exc:  # noqa: BLE001
                    summary["errors"].append(
                        {"stage": "table_extraction", "page": page_number, "warning": "parser_error", "error": str(exc)}
                    )
                    continue
                for local_table_index, table in enumerate(tables, start=1):
                    summary["tables_seen"] += 1
                    if not table or len(table) < 2:
                        summary["warnings"].append(
                            {"stage": "table_extraction", "page": page_number, "warning": "table_too_small"}
                        )
                        continue
                    raw_header = table[0]
                    headers, header_warnings = make_unique_headers(raw_header)
                    normalized_rows: list[dict[str, str]] = []
                    table_row_cards: list[dict[str, Any]] = []
                    for row_index, row in enumerate(table[1:], start=1):
                        if not any(clean_text(cell) for cell in row):
                            continue
                        row_data, cells, row_warnings = build_row_data(headers, list(row))
                        warnings = sorted(set(header_warnings + row_warnings))
                        card = construct_table_row_card(
                            report,
                            company,
                            page_number,
                            local_table_index,
                            row_index,
                            headers,
                            row_data,
                            cells,
                            warnings,
                        )
                        table_row_cards.append(card)
                        normalized_rows.append(row_data)
                    row_cards.extend(table_row_cards)
                    if include_table_markdown and normalized_rows:
                        markdown_cards.append(
                            construct_table_markdown_card(
                                report,
                                company,
                                page_number,
                                local_table_index,
                                headers,
                                normalized_rows,
                                header_warnings,
                            )
                        )
    except Exception as exc:  # noqa: BLE001
        summary["errors"].append({"stage": "table_extraction", "warning": "parser_error", "error": str(exc)})
    return row_cards, markdown_cards, summary


def assert_no_excluded_card_fields(card: dict[str, Any]) -> None:
    present = sorted(EXCLUDED_CARD_FIELDS & set(card.keys()))
    if present:
        fail(f"Evidence card contains excluded fields {present}: {card.get('evidence_id')}")


def register_cards(stats: PdfStats, cards: list[dict[str, Any]]) -> list[dict[str, Any]]:
    unique_cards: list[dict[str, Any]] = []
    for card in cards:
        evidence_id = clean_text(card.get("evidence_id"))
        if not evidence_id:
            fail("Evidence card missing evidence_id.")
        if evidence_id in stats.evidence_ids:
            stats.duplicate_evidence_ids_seen += 1
            continue
        assert_no_excluded_card_fields(card)
        stats.evidence_ids.add(evidence_id)
        evidence_type = clean_text(card.get("evidence_type"))
        stats.evidence_id_to_card_type[evidence_id] = evidence_type
        company_id = clean_text(card.get("company_id"))
        source_year = int(card.get("source_year"))
        stats.companies_written.add(company_id)
        stats.source_years_seen.add(source_year)

        # company_year_ids is used for package-manifest membership.
        # Table-row cards enter manifests only when they pass the conservative
        # main-index criteria; markdown cards are kept as audit/context refs.
        package_eligible = True
        if evidence_type == "pdf_table_row":
            package_eligible = bool(card.get("include_in_main_index", True))
        if package_eligible:
            stats.company_year_ids[company_id][source_year][evidence_type].append(evidence_id)

        if evidence_type == "narrative":
            stats.narrative_cards_written += 1
        elif evidence_type == "pdf_table_row":
            stats.table_row_cards_written += 1
            if card.get("manual_review_required"):
                stats.manual_review_required_cards += 1
            if not package_eligible:
                stats.main_index_excluded_cards += 1
        elif evidence_type == "pdf_table_markdown":
            stats.table_markdown_cards_written += 1
            if not card.get("include_in_main_index", False):
                stats.main_index_excluded_cards += 1
        unique_cards.append(card)
    return unique_cards


def write_cards(
    evidence_root: Path,
    company: CompanyMeta,
    cards: list[dict[str, Any]],
    stats: PdfStats,
    *,
    overwrite: bool,
) -> None:
    if not cards:
        return
    by_type: dict[str, list[dict[str, Any]]] = defaultdict(list)
    by_type_year: dict[tuple[str, int], list[dict[str, Any]]] = defaultdict(list)
    for card in cards:
        evidence_type = clean_text(card["evidence_type"])
        source_year = int(card["source_year"])
        by_type[evidence_type].append(card)
        by_type_year[(evidence_type, source_year)].append(card)

    base = company_root(evidence_root, company) / "pdf" / "evidence_cards"
    filename_by_type = {
        "narrative": "pdf_narrative_cards.jsonl",
        "pdf_table_row": "pdf_table_row_cards.jsonl",
        "pdf_table_markdown": "pdf_table_markdown_cards.jsonl",
    }
    by_year_suffix = {
        "narrative": "narrative",
        "pdf_table_row": "table_rows",
        "pdf_table_markdown": "table_markdown",
    }
    for evidence_type, records in by_type.items():
        append_jsonl(base / filename_by_type[evidence_type], records, stats, overwrite=overwrite)
    for (evidence_type, year), records in by_type_year.items():
        append_jsonl(base / "by_year" / f"{year}_{by_year_suffix[evidence_type]}.jsonl", records, stats, overwrite=overwrite)

    canonical = canonical_paths(evidence_root)
    if by_type.get("narrative"):
        append_jsonl(canonical["all_narrative"], by_type["narrative"], stats, overwrite=overwrite)
    if by_type.get("pdf_table_row"):
        append_jsonl(canonical["all_table_rows"], by_type["pdf_table_row"], stats, overwrite=overwrite)
    if by_type.get("pdf_table_markdown"):
        append_jsonl(canonical["all_table_markdown"], by_type["pdf_table_markdown"], stats, overwrite=overwrite)
    append_jsonl(canonical["all_pdf_cards"], cards, stats, overwrite=overwrite)


def write_pdf_extraction_summary(
    evidence_root: Path,
    company: CompanyMeta,
    report: ReportMeta,
    payload: dict[str, Any],
    *,
    overwrite: bool,
) -> None:
    path = (
        company_root(evidence_root, company)
        / "pdf"
        / "source_docs"
        / str(report.source_year)
        / f"{Path(report.source_file).stem}.extraction_summary.json"
    )
    write_json(path, payload, overwrite=overwrite)


def make_pdf_report_worker_task(
    task_index: int,
    report: ReportMeta,
    company: CompanyMeta,
    args: argparse.Namespace,
) -> dict[str, Any]:
    """Create a pickle-safe worker task for exactly one PDF report."""

    return {
        "task_index": task_index,
        "report": report,
        "company": company,
        "config": {
            "extract_tables": bool(args.extract_tables),
            "include_table_markdown": bool(args.include_table_markdown),
            "include_short_narrative": bool(args.include_short_narrative),
            "narrative_min_words": int(args.narrative_min_words),
            "narrative_max_words": int(args.narrative_max_words),
            "narrative_min_chars": int(args.narrative_min_chars),
            "max_pages_per_pdf": args.max_pages_per_pdf,
        },
    }


def process_pdf_report_task(task: dict[str, Any]) -> dict[str, Any]:
    """Extract cards for one PDF report without writing shared output files.

    This function is intentionally side-effect free. It is safe to run in a
    ProcessPoolExecutor worker because it only reads one PDF and returns cards,
    extraction diagnostics, and per-PDF counters to the main process. The main
    process remains responsible for evidence ID registration, JSONL writing,
    package manifest updates, and global integrity reports.
    """

    task_index = int(task["task_index"])
    report: ReportMeta = task["report"]
    company: CompanyMeta = task["company"]
    config: dict[str, Any] = task["config"]

    extraction_summary: dict[str, Any] = {
        "source_file": report.source_file,
        "company_id": report.company_id,
        "company_name": company.company_name,
        "source_year": report.source_year,
        "document_type": report.document_type,
        "document_title": report.document_title,
        "pdf_path": str(report.pdf_path),
        "extraction_status": "started",
        "pages_total": 0,
        "pages_processed": 0,
        "narrative_cards_written": 0,
        "table_row_cards_written": 0,
        "table_markdown_cards_written": 0,
        "extraction_methods": {
            "text": NARRATIVE_EXTRACTION_METHOD,
            "tables": TABLE_EXTRACTION_METHOD if config["extract_tables"] else None,
        },
        "warnings": [],
        "errors": [],
        "created_at": now_utc_iso(),
        "schema_version": "pdf_extraction_summary_v1",
    }

    result: dict[str, Any] = {
        "task_index": task_index,
        "report": report,
        "company": company,
        "cards": [],
        "extraction_summary": extraction_summary,
        "failed": False,
        "pages_seen": 0,
        "pages_processed": 0,
        "pages_with_empty_text": 0,
        "table_extraction_failures": 0,
    }

    try:
        blocks, text_summary = extract_pdf_text_blocks(report.pdf_path, config["max_pages_per_pdf"])
        extraction_summary["pages_total"] = text_summary.get("pages_total", 0)
        extraction_summary["pages_processed"] = text_summary.get("pages_processed", 0)
        extraction_summary["warnings"].extend(text_summary.get("warnings", []))
        extraction_summary["errors"].extend(text_summary.get("errors", []))
        result["pages_seen"] = int(text_summary.get("pages_total", 0) or 0)
        result["pages_processed"] = int(text_summary.get("pages_processed", 0) or 0)
        result["pages_with_empty_text"] = sum(
            1 for warning in text_summary.get("warnings", []) if warning.get("warning") == "empty_extracted_text"
        )

        narrative_chunks = make_narrative_chunks(
            blocks,
            min_words=config["narrative_min_words"],
            max_words=config["narrative_max_words"],
            min_chars=config["narrative_min_chars"],
            include_short=config["include_short_narrative"],
        )
        narrative_cards = [
            construct_narrative_card(chunk, index, report, company)
            for index, chunk in enumerate(narrative_chunks, start=1)
        ]

        table_row_cards: list[dict[str, Any]] = []
        table_markdown_cards: list[dict[str, Any]] = []
        if config["extract_tables"]:
            table_row_cards, table_markdown_cards, table_summary = extract_table_cards(
                report,
                company,
                max_pages=config["max_pages_per_pdf"],
                include_table_markdown=config["include_table_markdown"],
            )
            extraction_summary["warnings"].extend(table_summary.get("warnings", []))
            extraction_summary["errors"].extend(table_summary.get("errors", []))
            result["table_extraction_failures"] = len(table_summary.get("errors", []))

        cards = narrative_cards + table_row_cards + table_markdown_cards
        extraction_summary["narrative_cards_written"] = len(narrative_cards)
        extraction_summary["table_row_cards_written"] = len(table_row_cards)
        extraction_summary["table_markdown_cards_written"] = len(table_markdown_cards)

        if extraction_summary["errors"]:
            extraction_summary["extraction_status"] = "completed_with_errors"
        elif extraction_summary["warnings"]:
            extraction_summary["extraction_status"] = "completed_with_warnings"
        else:
            extraction_summary["extraction_status"] = "completed"

        result["cards"] = cards
        return result
    except Exception as exc:  # noqa: BLE001
        result["failed"] = True
        extraction_summary["extraction_status"] = "failed"
        extraction_summary["errors"].append(
            {"stage": "pdf_processing", "warning": "parser_error", "error": str(exc)}
        )
        return result


def update_stats_from_worker_result(stats: PdfStats, result: dict[str, Any]) -> None:
    """Add non-card extraction counters from one worker result to global stats."""

    stats.pages_seen += int(result.get("pages_seen", 0) or 0)
    stats.pages_processed += int(result.get("pages_processed", 0) or 0)
    stats.pages_with_empty_text += int(result.get("pages_with_empty_text", 0) or 0)
    stats.table_extraction_failures += int(result.get("table_extraction_failures", 0) or 0)


def build_pdf_cards(
    args: argparse.Namespace,
    paths: dict[str, Path],
    companies: dict[str, CompanyMeta],
    stats: PdfStats,
) -> tuple[PdfStats, dict[str, CompanyMeta]]:
    source_years = required_pdf_source_years(args)
    reports = load_report_inventory(
        paths["report_inventory"],
        paths["reports_dir"],
        companies,
        source_years,
        args.include_unlisted_pdfs,
        stats,
    )
    if args.mode == "pilot" and args.max_pdfs is None:
        args.max_pdfs = 5
    if args.max_pdfs is not None:
        reports = reports[: args.max_pdfs]
        stats.pdfs_selected = len(reports)

    write_company_metadata_files(args.evidence_root, companies, overwrite=args.overwrite)
    worker_count = min(int(args.workers), len(reports)) if reports else 1
    progress = ProgressTracker(len(reports), "PDF evidence", args.progress_style)
    if len(reports) > 0:
        pass_check(
            "pdf_worker_configuration",
            f"processing {len(reports):,} PDFs with {worker_count} worker(s), chunksize={args.worker_chunksize}",
        )

    tasks: list[dict[str, Any]] = []
    for task_index, report in enumerate(reports):
        company = companies.get(report.company_id)
        if company is None:
            continue
        tasks.append(make_pdf_report_worker_task(task_index, report, company, args))

    if worker_count <= 1:
        result_iterable = map(process_pdf_report_task, tasks)
    else:
        executor = ProcessPoolExecutor(max_workers=worker_count)
        result_iterable = executor.map(process_pdf_report_task, tasks, chunksize=args.worker_chunksize)

    try:
        for result in result_iterable:
            report: ReportMeta = result["report"]
            company: CompanyMeta = result["company"]
            extraction_summary: dict[str, Any] = result["extraction_summary"]

            update_stats_from_worker_result(stats, result)
            cards = result.get("cards", [])
            all_cards = register_cards(stats, cards)
            write_cards(args.evidence_root, company, all_cards, stats, overwrite=args.overwrite)

            # After global duplicate-ID registration, keep the per-PDF summary
            # aligned with the cards actually written by the main process.
            extraction_summary["narrative_cards_written"] = len(
                [card for card in all_cards if card["evidence_type"] == "narrative"]
            )
            extraction_summary["table_row_cards_written"] = len(
                [card for card in all_cards if card["evidence_type"] == "pdf_table_row"]
            )
            extraction_summary["table_markdown_cards_written"] = len(
                [card for card in all_cards if card["evidence_type"] == "pdf_table_markdown"]
            )

            if result.get("failed"):
                stats.pdfs_failed += 1
                stats.errors.extend(
                    {**error, "source_file": report.source_file, "company_id": report.company_id}
                    for error in extraction_summary.get("errors", [])
                )
            else:
                stats.pdfs_processed += 1
                if extraction_summary.get("errors"):
                    stats.errors.extend(
                        {**error, "source_file": report.source_file, "company_id": report.company_id}
                        for error in extraction_summary.get("errors", [])
                    )
                stats.warnings.extend(
                    {**warning, "source_file": report.source_file, "company_id": report.company_id}
                    for warning in extraction_summary.get("warnings", [])
                )

            write_pdf_extraction_summary(args.evidence_root, company, report, extraction_summary, overwrite=args.overwrite)
            detail = (
                f"{report.source_file} narrative={extraction_summary['narrative_cards_written']} "
                f"tables={extraction_summary['table_row_cards_written']}"
            )
            progress.update(detail)
    finally:
        if worker_count > 1:
            executor.shutdown(wait=True)

    write_pdf_build_summary(args, paths, stats, companies)
    run_canonical_integrity_checks(args, stats)
    pass_check("phase_3_narrative_cards", f"{stats.narrative_cards_written:,} narrative cards written")
    if args.extract_tables:
        pass_check("phase_4_table_cards", f"{stats.table_row_cards_written:,} table row cards written")
    pass_check("phase_5_canonical_storage", f"canonical PDF outputs written under {canonical_paths(args.evidence_root)['root']}")
    return stats, companies


def write_pdf_build_summary(
    args: argparse.Namespace,
    paths: dict[str, Path],
    stats: PdfStats,
    companies: dict[str, CompanyMeta],
) -> None:
    canonical = canonical_paths(args.evidence_root)
    canonical["indexes"].mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    for company_id, company in companies.items():
        year_counts: dict[int, dict[str, int]] = {}
        for year, by_type in sorted(stats.company_year_ids.get(company_id, {}).items()):
            year_counts[int(year)] = {evidence_type: len(ids) for evidence_type, ids in sorted(by_type.items())}
        rows.append(
            {
                "company_id": company_id,
                "company_slug": company.company_slug,
                "company_name": company.company_name,
                "pdf_narrative_cards": sum(counts.get("narrative", 0) for counts in year_counts.values()),
                "pdf_table_row_cards": sum(counts.get("pdf_table_row", 0) for counts in year_counts.values()),
                "pdf_table_markdown_cards": sum(counts.get("pdf_table_markdown", 0) for counts in year_counts.values()),
                "source_years_with_cards": json.dumps(sorted(year_counts.keys())),
                "cards_by_source_year": json.dumps(year_counts, sort_keys=True),
            }
        )
    pd.DataFrame(rows).to_csv(canonical["summary"], index=False)

    inventory_rows = []
    for company_id, years in sorted(stats.company_year_ids.items()):
        for year, by_type in sorted(years.items()):
            inventory_rows.append(
                {
                    "company_id": company_id,
                    "source_year": year,
                    "pdf_narrative_cards": len(by_type.get("narrative", [])),
                    "pdf_table_row_cards": len(by_type.get("pdf_table_row", [])),
                    "pdf_table_markdown_cards": len(by_type.get("pdf_table_markdown", [])),
                }
            )
    pd.DataFrame(inventory_rows).to_csv(canonical["inventory_summary"], index=False)

    report = {
        "script_version": SCRIPT_VERSION,
        "schema_version": PDF_INTEGRITY_SCHEMA_VERSION,
        "created_at": now_utc_iso(),
        "input_files": {
            "companies": str(paths.get("companies")),
            "reports_dir": str(paths.get("reports_dir")),
            "report_inventory": str(paths.get("report_inventory")),
        },
        "pdfs_seen": stats.pdfs_seen,
        "pdfs_selected": stats.pdfs_selected,
        "pdfs_processed": stats.pdfs_processed,
        "pdfs_failed": stats.pdfs_failed,
        "missing_pdf_files": stats.missing_pdf_files,
        "unparseable_pdf_files": stats.unparseable_pdf_files,
        "pages_seen": stats.pages_seen,
        "pages_processed": stats.pages_processed,
        "pages_with_empty_text": stats.pages_with_empty_text,
        "narrative_cards_written": stats.narrative_cards_written,
        "table_row_cards_written": stats.table_row_cards_written,
        "table_markdown_cards_written": stats.table_markdown_cards_written,
        "table_extraction_failures": stats.table_extraction_failures,
        "manual_review_required_cards": stats.manual_review_required_cards,
        "main_index_excluded_cards": stats.main_index_excluded_cards,
        "duplicate_evidence_ids_seen": stats.duplicate_evidence_ids_seen,
        "selected_company_count": len(companies),
        "source_years_seen": sorted(stats.source_years_seen),
        "required_pdf_source_years": required_pdf_source_years(args),
        "warnings_sample": stats.warnings[:100],
        "errors_sample": stats.errors[:100],
        "acceptance_criteria": ACCEPTANCE_CRITERIA,
    }
    write_json(canonical["integrity"], report, overwrite=True)


def run_canonical_integrity_checks(args: argparse.Namespace, stats: PdfStats) -> None:
    if stats.duplicate_evidence_ids_seen:
        fail(f"Duplicate PDF evidence IDs detected: {stats.duplicate_evidence_ids_seen:,}")
    if args.mode in {"cards-and-packages", "cards-only", "pilot"} and stats.pdfs_selected and stats.pdfs_processed == 0:
        warn_check("pdf_cards_empty", "no PDFs were processed; check selected companies, source years, and report files")
    canonical = canonical_paths(args.evidence_root)
    if not canonical["summary"].exists():
        fail(f"PDF build summary missing: {canonical['summary']}")
    if not canonical["integrity"].exists():
        fail(f"PDF integrity report missing: {canonical['integrity']}")

    # Validate narrative baseline for cards produced in this run by scanning the touched narrative index if present.
    if canonical["all_narrative"] in stats.touched_files and canonical["all_narrative"].exists():
        with canonical["all_narrative"].open("r", encoding="utf-8") as source:
            for line in source:
                if not line.strip():
                    continue
                card = json.loads(line)
                if card.get("retrieval_text") != card.get("original_text"):
                    fail(f"Narrative retrieval_text != original_text for {card.get('evidence_id')}")

    if canonical["all_table_rows"] in stats.touched_files and canonical["all_table_rows"].exists():
        with canonical["all_table_rows"].open("r", encoding="utf-8") as source:
            for line in source:
                if not line.strip():
                    continue
                card = json.loads(line)
                for required in ["column_headers", "row_data", "cells"]:
                    if required not in card:
                        fail(f"Table row card missing {required}: {card.get('evidence_id')}")
                if "dimensions" in card or "structured_values" in card:
                    fail(f"Table row card uses deprecated semantic fields: {card.get('evidence_id')}")
    pass_check("phase_7_integrity_checks", "canonical PDF card schema and diagnostics validated")


def load_existing_pdf_index(evidence_root: Path, selected_ids: set[str] | None) -> tuple[PdfStats, dict[str, CompanyMeta]]:
    canonical = canonical_paths(evidence_root)
    if not canonical["all_pdf_cards"].exists():
        fail(f"Cannot use packages-only because PDF canonical index is missing: {canonical['all_pdf_cards']}")

    stats = PdfStats()
    companies: dict[str, CompanyMeta] = {}
    with canonical["all_pdf_cards"].open("r", encoding="utf-8") as source:
        for line in source:
            if not line.strip():
                continue
            card = json.loads(line)
            company_id = clean_text(card.get("company_id"))
            if selected_ids is not None and company_id not in selected_ids:
                continue
            evidence_id = clean_text(card.get("evidence_id"))
            source_year = int(card.get("source_year"))
            evidence_type = clean_text(card.get("evidence_type"))
            stats.evidence_ids.add(evidence_id)
            stats.evidence_id_to_card_type[evidence_id] = evidence_type
            package_eligible = True
            if evidence_type == "pdf_table_row":
                package_eligible = bool(card.get("include_in_main_index", True))
            if package_eligible:
                stats.company_year_ids[company_id][source_year][evidence_type].append(evidence_id)
            stats.companies_written.add(company_id)
            stats.source_years_seen.add(source_year)
            if evidence_type == "narrative":
                stats.narrative_cards_written += 1
            elif evidence_type == "pdf_table_row":
                stats.table_row_cards_written += 1
                if not package_eligible:
                    stats.main_index_excluded_cards += 1
            elif evidence_type == "pdf_table_markdown":
                stats.table_markdown_cards_written += 1
            if company_id not in companies:
                companies[company_id] = CompanyMeta(
                    company_id=company_id,
                    company_slug=clean_text(card.get("company_slug")) or slugify(clean_text(card.get("company_name"))),
                    company_name=clean_text(card.get("company_name")) or company_id,
                    isin=clean_text(card.get("isin")) or None,
                    country=clean_text(card.get("country")) or None,
                    primary_sics_sector=clean_text(card.get("primary_sics_sector")) or None,
                    source_dataset=str(canonical["all_pdf_cards"]),
                )
    pass_check(
        "phase_3_narrative_cards",
        f"reused {stats.narrative_cards_written:,} narrative cards from existing canonical PDF index",
    )
    pass_check(
        "phase_4_table_cards",
        f"reused {stats.table_row_cards_written:,} table row cards from existing canonical PDF index",
    )
    return stats, companies


def select_card_ids_for_manifest(
    stats: PdfStats,
    company_id: str,
    pdf_years: list[int],
    evidence_type: str,
) -> list[str]:
    ids: list[str] = []
    for year in pdf_years:
        ids.extend(stats.company_year_ids.get(company_id, {}).get(year, {}).get(evidence_type, []))
    return sorted(ids)


def update_package_manifests(args: argparse.Namespace, stats: PdfStats) -> None:
    build_name = args.build_name or generated_build_name(args)
    build_root = args.evidence_root / "builds" / build_name
    if not build_root.exists():
        fail(f"Build folder does not exist: {build_root}")

    all_pdf_ids = set(stats.evidence_ids)
    package_rows: list[dict[str, Any]] = []
    manifest_count = 0
    missing_refs = 0
    errors: list[str] = []

    for manifest_path in sorted(build_root.glob("companies/*/manifests/package_*.json")):
        manifest_count += 1
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        company_id = clean_text(manifest.get("company_id"))
        target_year = int(manifest.get("target_reporting_year"))
        expected_pdf_years = rolling_years(target_year, args.pdf_window_years, args.pdf_lag_years)
        pdf_years = [int(year) for year in manifest.get("included_source_years", {}).get("pdf", [])]
        if pdf_years != expected_pdf_years:
            errors.append(f"{manifest_path}: PDF years do not match rolling-window rule.")
        if args.pdf_lag_years > 0 and target_year in pdf_years:
            errors.append(f"{manifest_path}: target year appears in PDF source years despite positive pdf lag.")

        narrative_ids = select_card_ids_for_manifest(stats, company_id, pdf_years, "narrative")
        table_row_ids = select_card_ids_for_manifest(stats, company_id, pdf_years, "pdf_table_row")
        table_markdown_ids = select_card_ids_for_manifest(stats, company_id, pdf_years, "pdf_table_markdown")

        # Keep only references known in the canonical PDF index.
        for evidence_id in narrative_ids + table_row_ids + table_markdown_ids:
            if evidence_id not in all_pdf_ids:
                missing_refs += 1

        manifest.setdefault("evidence_card_ids", {})
        manifest["evidence_card_ids"]["pdf_narrative"] = narrative_ids
        manifest["evidence_card_ids"]["pdf_table_row"] = table_row_ids
        manifest["evidence_card_ids"]["pdf_table_markdown"] = table_markdown_ids

        manifest.setdefault("evidence_card_counts", {})
        csv_count = int(manifest["evidence_card_counts"].get("csv_metric", 0))
        manifest["evidence_card_counts"].update(
            {
                "pdf_narrative": len(narrative_ids),
                "pdf_table_row": len(table_row_ids),
                "pdf_table_markdown": len(table_markdown_ids),
                # Main retrievable cards exclude table_markdown context cards by design.
                "total": csv_count + len(narrative_ids) + len(table_row_ids),
            }
        )
        manifest.setdefault("source_status", {})
        manifest["source_status"]["pdf_status"] = "implemented"
        notes = manifest.setdefault("notes", [])
        pdf_note = "PDF cards are canonical source-centric records generated by pdf_2_evidence.py."
        if pdf_note not in notes:
            notes.append(pdf_note)
        write_json(manifest_path, manifest, overwrite=True)

        package_rows.append(
            {
                "package_id": manifest.get("package_id"),
                "build_name": manifest.get("build_name", build_name),
                "company_id": company_id,
                "company_slug": manifest.get("company_slug"),
                "company_name": manifest.get("company_name"),
                "target_reporting_year": target_year,
                "csv_source_years": json.dumps(manifest.get("included_source_years", {}).get("csv", [])),
                "pdf_source_years": json.dumps(pdf_years),
                "csv_metric_cards": csv_count,
                "pdf_narrative_cards": len(narrative_ids),
                "pdf_table_row_cards": len(table_row_ids),
                "pdf_table_markdown_cards": len(table_markdown_ids),
                "total_cards": csv_count + len(narrative_ids) + len(table_row_ids),
                "manifest_path": str(manifest_path),
            }
        )

    if errors:
        fail("Package manifest PDF integrity errors:\n" + "\n".join(errors[:20]))
    if missing_refs:
        fail(f"Package manifests contain missing canonical PDF references: {missing_refs:,}")

    if package_rows:
        pd.DataFrame(package_rows).to_csv(build_root / "package_index.csv", index=False)

    package_report = {
        "script_version": SCRIPT_VERSION,
        "schema_version": "pdf_package_integrity_report_v1",
        "created_at": now_utc_iso(),
        "build_name": build_name,
        "manifest_count": manifest_count,
        "pdf_evidence_ids_available": len(all_pdf_ids),
        "total_pdf_narrative_refs": sum(row["pdf_narrative_cards"] for row in package_rows),
        "total_pdf_table_row_refs": sum(row["pdf_table_row_cards"] for row in package_rows),
        "total_pdf_table_markdown_refs": sum(row["pdf_table_markdown_cards"] for row in package_rows),
        "notes": ["total_cards excludes pdf_table_markdown audit/context cards."],
    }
    write_json(build_root / "pdf_package_integrity_report.json", package_report, overwrite=True)
    pass_check("phase_6_package_manifest_update", f"{manifest_count:,} package manifests updated under {build_root}")


def main() -> None:
    args = parse_args()
    acceptance_report()
    paths = validate_args_and_paths(args)

    selected_ids, selected_overrides = load_selected_company_table(args.selected_company_ids)
    companies: dict[str, CompanyMeta]
    stats: PdfStats

    if args.mode == "packages-only":
        stats, _ = load_existing_pdf_index(args.evidence_root, selected_ids)
    else:
        companies = load_company_metadata(
            paths["companies"],
            selected_ids,
            selected_overrides,
            args.company_limit,
        )
        stats = PdfStats()
        stats, _ = build_pdf_cards(args, paths, companies, stats)

    if args.mode in {"cards-and-packages", "packages-only"}:
        update_package_manifests(args, stats)

    print("\nDone.")


if __name__ == "__main__":
    main()
